// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: recommendation.proto

package recommendation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The requirement of the recommendation.
type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Require       string                 `protobuf:"bytes,1,opt,name=require,proto3" json:"require,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_recommendation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetRequire() string {
	if x != nil {
		return x.Require
	}
	return ""
}

func (x *Request) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Request) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelIds      []string               `protobuf:"bytes,1,rep,name=HotelIds,proto3" json:"HotelIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_recommendation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_recommendation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_recommendation_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetHotelIds() []string {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

var File_recommendation_proto protoreflect.FileDescriptor

const file_recommendation_proto_rawDesc = "" +
	"\n" +
	"\x14recommendation.proto\x12\x0erecommendation\"G\n" +
	"\aRequest\x12\x18\n" +
	"\arequire\x18\x01 \x01(\tR\arequire\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\"$\n" +
	"\x06Result\x12\x1a\n" +
	"\bHotelIds\x18\x01 \x03(\tR\bHotelIds2W\n" +
	"\x0eRecommendation\x12E\n" +
	"\x12GetRecommendations\x12\x17.recommendation.Request\x1a\x16.recommendation.ResultB\x12Z\x10./recommendationb\x06proto3"

var (
	file_recommendation_proto_rawDescOnce sync.Once
	file_recommendation_proto_rawDescData []byte
)

func file_recommendation_proto_rawDescGZIP() []byte {
	file_recommendation_proto_rawDescOnce.Do(func() {
		file_recommendation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_recommendation_proto_rawDesc), len(file_recommendation_proto_rawDesc)))
	})
	return file_recommendation_proto_rawDescData
}

var file_recommendation_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_recommendation_proto_goTypes = []any{
	(*Request)(nil), // 0: recommendation.Request
	(*Result)(nil),  // 1: recommendation.Result
}
var file_recommendation_proto_depIdxs = []int32{
	0, // 0: recommendation.Recommendation.GetRecommendations:input_type -> recommendation.Request
	1, // 1: recommendation.Recommendation.GetRecommendations:output_type -> recommendation.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_recommendation_proto_init() }
func file_recommendation_proto_init() {
	if File_recommendation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_recommendation_proto_rawDesc), len(file_recommendation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_recommendation_proto_goTypes,
		DependencyIndexes: file_recommendation_proto_depIdxs,
		MessageInfos:      file_recommendation_proto_msgTypes,
	}.Build()
	File_recommendation_proto = out.File
	file_recommendation_proto_goTypes = nil
	file_recommendation_proto_depIdxs = nil
}
