// Code generated by protoc-gen-arpc. DO NOT EDIT.
package recommendation

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
)

// RecommendationClient is the client API for Recommendation service.
type RecommendationClient interface {
	GetRecommendations(ctx context.Context, req *Request) (*Result, error)
}

type arpcRecommendationClient struct {
	client *rpc.Client
}

func NewRecommendationClient(client *rpc.Client) RecommendationClient {
	return &arpcRecommendationClient{client: client}
}

func (c *arpcRecommendationClient) GetRecommendations(ctx context.Context, req *Request) (*Result, error) {
	resp := new(Result)
	if err := c.client.Call(ctx, "Recommendation", "GetRecommendations", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type RecommendationServer interface {
	GetRecommendations(ctx context.Context, req *Request) (*Result, context.Context, error)
}

func RegisterRecommendationServer(s *rpc.Server, srv RecommendationServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Recommendation",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"GetRecommendations": {
				MethodName: "GetRecommendations",
				Handler:    _Recommendation_GetRecommendations_Handler,
			},
		},
	}, srv)
}
func _Recommendation_GetRecommendations_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(RecommendationServer).GetRecommendations(ctx, in)
	return out, newCtx, err
}
