// Code generated by protoc-gen-arpc. DO NOT EDIT.
package geo

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
)

// GeoClient is the client API for Geo service.
type GeoClient interface {
	Nearby(ctx context.Context, req *Request) (*Result, error)
}

type arpcGeoClient struct {
	client *rpc.Client
}

func NewGeoClient(client *rpc.Client) GeoClient {
	return &arpcGeoClient{client: client}
}

func (c *arpcGeoClient) Nearby(ctx context.Context, req *Request) (*Result, error) {
	resp := new(Result)
	if err := c.client.Call(ctx, "Geo", "Nearby", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type GeoServer interface {
	Nearby(ctx context.Context, req *Request) (*Result, context.Context, error)
}

func RegisterGeoServer(s *rpc.Server, srv GeoServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Geo",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"Nearby": {
				MethodName: "Nearby",
				Handler:    _Geo_Nearby_Handler,
			},
		},
	}, srv)
}
func _Geo_Nearby_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(GeoServer).Nearby(ctx, in)
	return out, newCtx, err
}
