// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: profile.proto

package profile

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelIds      []string               `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_profile_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetHotelIds() []string {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

func (x *Request) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type Result struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	StreetNumber  string                 `protobuf:"bytes,5,opt,name=streetNumber,proto3" json:"streetNumber,omitempty"`
	StreetName    string                 `protobuf:"bytes,6,opt,name=streetName,proto3" json:"streetName,omitempty"`
	City          string                 `protobuf:"bytes,7,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,8,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,9,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,10,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Lat           float32                `protobuf:"fixed32,11,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,12,opt,name=lon,proto3" json:"lon,omitempty"`
	ImagesUrl     []string               `protobuf:"bytes,13,rep,name=images_url,json=imagesUrl,proto3" json:"images_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_profile_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_profile_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_profile_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Result) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Result) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Result) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Result) GetStreetNumber() string {
	if x != nil {
		return x.StreetNumber
	}
	return ""
}

func (x *Result) GetStreetName() string {
	if x != nil {
		return x.StreetName
	}
	return ""
}

func (x *Result) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Result) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Result) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Result) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Result) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Result) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *Result) GetImagesUrl() []string {
	if x != nil {
		return x.ImagesUrl
	}
	return nil
}

var File_profile_proto protoreflect.FileDescriptor

const file_profile_proto_rawDesc = "" +
	"\n" +
	"\rprofile.proto\x12\aprofile\"=\n" +
	"\aRequest\x12\x1a\n" +
	"\bhotelIds\x18\x01 \x03(\tR\bhotelIds\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"\xdb\x02\n" +
	"\x06Result\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vphoneNumber\x18\x03 \x01(\tR\vphoneNumber\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\"\n" +
	"\fstreetNumber\x18\x05 \x01(\tR\fstreetNumber\x12\x1e\n" +
	"\n" +
	"streetName\x18\x06 \x01(\tR\n" +
	"streetName\x12\x12\n" +
	"\x04city\x18\a \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\b \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\t \x01(\tR\acountry\x12\x1e\n" +
	"\n" +
	"postalCode\x18\n" +
	" \x01(\tR\n" +
	"postalCode\x12\x10\n" +
	"\x03lat\x18\v \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\f \x01(\x02R\x03lon\x12\x1d\n" +
	"\n" +
	"images_url\x18\r \x03(\tR\timagesUrl2;\n" +
	"\aProfile\x120\n" +
	"\vGetProfiles\x12\x10.profile.Request\x1a\x0f.profile.ResultB\vZ\t./profileb\x06proto3"

var (
	file_profile_proto_rawDescOnce sync.Once
	file_profile_proto_rawDescData []byte
)

func file_profile_proto_rawDescGZIP() []byte {
	file_profile_proto_rawDescOnce.Do(func() {
		file_profile_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)))
	})
	return file_profile_proto_rawDescData
}

var file_profile_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_profile_proto_goTypes = []any{
	(*Request)(nil), // 0: profile.Request
	(*Result)(nil),  // 1: profile.Result
}
var file_profile_proto_depIdxs = []int32{
	0, // 0: profile.Profile.GetProfiles:input_type -> profile.Request
	1, // 1: profile.Profile.GetProfiles:output_type -> profile.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profile_proto_init() }
func file_profile_proto_init() {
	if File_profile_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profile_proto_rawDesc), len(file_profile_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profile_proto_goTypes,
		DependencyIndexes: file_profile_proto_depIdxs,
		MessageInfos:      file_profile_proto_msgTypes,
	}.Build()
	File_profile_proto = out.File
	file_profile_proto_goTypes = nil
	file_profile_proto_depIdxs = nil
}
