// Code generated by protoc-gen-arpc. DO NOT EDIT.
package profile

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
)

// ProfileClient is the client API for Profile service.
type ProfileClient interface {
	GetProfiles(ctx context.Context, req *Request) (*Result, error)
}

type arpcProfileClient struct {
	client *rpc.Client
}

func NewProfileClient(client *rpc.Client) ProfileClient {
	return &arpcProfileClient{client: client}
}

func (c *arpcProfileClient) GetProfiles(ctx context.Context, req *Request) (*Result, error) {
	resp := new(Result)
	if err := c.client.Call(ctx, "Profile", "GetProfiles", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type ProfileServer interface {
	GetProfiles(ctx context.Context, req *Request) (*Result, context.Context, error)
}

func RegisterProfileServer(s *rpc.Server, srv ProfileServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Profile",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"GetProfiles": {
				MethodName: "GetProfiles",
				Handler:    _Profile_GetProfiles_Handler,
			},
		},
	}, srv)
}
func _Profile_GetProfiles_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(ProfileServer).GetProfiles(ctx, in)
	return out, newCtx, err
}
