// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.6.1
// source: rate.proto

package rate

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelIds      []string               `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	InDate        string                 `protobuf:"bytes,2,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate       string                 `protobuf:"bytes,3,opt,name=outDate,proto3" json:"outDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_rate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{0}
}

func (x *Request) GetHotelIds() []string {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

func (x *Request) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *Request) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

type Result struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	HotelId            string                 `protobuf:"bytes,1,opt,name=hotelId,proto3" json:"hotelId,omitempty"`
	Code               string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	InDate             string                 `protobuf:"bytes,3,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate            string                 `protobuf:"bytes,4,opt,name=outDate,proto3" json:"outDate,omitempty"`
	BookableRate       float64                `protobuf:"fixed64,5,opt,name=bookableRate,proto3" json:"bookableRate,omitempty"`
	TotalRate          float64                `protobuf:"fixed64,6,opt,name=totalRate,proto3" json:"totalRate,omitempty"`
	TotalRateInclusive float64                `protobuf:"fixed64,7,opt,name=totalRateInclusive,proto3" json:"totalRateInclusive,omitempty"`
	Currency           string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	RoomDescription    string                 `protobuf:"bytes,9,opt,name=roomDescription,proto3" json:"roomDescription,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Result) Reset() {
	*x = Result{}
	mi := &file_rate_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Result) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Result) ProtoMessage() {}

func (x *Result) ProtoReflect() protoreflect.Message {
	mi := &file_rate_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Result.ProtoReflect.Descriptor instead.
func (*Result) Descriptor() ([]byte, []int) {
	return file_rate_proto_rawDescGZIP(), []int{1}
}

func (x *Result) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *Result) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Result) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *Result) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

func (x *Result) GetBookableRate() float64 {
	if x != nil {
		return x.BookableRate
	}
	return 0
}

func (x *Result) GetTotalRate() float64 {
	if x != nil {
		return x.TotalRate
	}
	return 0
}

func (x *Result) GetTotalRateInclusive() float64 {
	if x != nil {
		return x.TotalRateInclusive
	}
	return 0
}

func (x *Result) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Result) GetRoomDescription() string {
	if x != nil {
		return x.RoomDescription
	}
	return ""
}

var File_rate_proto protoreflect.FileDescriptor

const file_rate_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"rate.proto\x12\x04rate\"W\n" +
	"\aRequest\x12\x1a\n" +
	"\bhotelIds\x18\x01 \x03(\tR\bhotelIds\x12\x16\n" +
	"\x06inDate\x18\x02 \x01(\tR\x06inDate\x12\x18\n" +
	"\aoutDate\x18\x03 \x01(\tR\aoutDate\"\xa0\x02\n" +
	"\x06Result\x12\x18\n" +
	"\ahotelId\x18\x01 \x01(\tR\ahotelId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06inDate\x18\x03 \x01(\tR\x06inDate\x12\x18\n" +
	"\aoutDate\x18\x04 \x01(\tR\aoutDate\x12\"\n" +
	"\fbookableRate\x18\x05 \x01(\x01R\fbookableRate\x12\x1c\n" +
	"\ttotalRate\x18\x06 \x01(\x01R\ttotalRate\x12.\n" +
	"\x12totalRateInclusive\x18\a \x01(\x01R\x12totalRateInclusive\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12(\n" +
	"\x0froomDescription\x18\t \x01(\tR\x0froomDescription2/\n" +
	"\x04Rate\x12'\n" +
	"\bGetRates\x12\r.rate.Request\x1a\f.rate.ResultB\bZ\x06./rateb\x06proto3"

var (
	file_rate_proto_rawDescOnce sync.Once
	file_rate_proto_rawDescData []byte
)

func file_rate_proto_rawDescGZIP() []byte {
	file_rate_proto_rawDescOnce.Do(func() {
		file_rate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rate_proto_rawDesc), len(file_rate_proto_rawDesc)))
	})
	return file_rate_proto_rawDescData
}

var file_rate_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rate_proto_goTypes = []any{
	(*Request)(nil), // 0: rate.Request
	(*Result)(nil),  // 1: rate.Result
}
var file_rate_proto_depIdxs = []int32{
	0, // 0: rate.Rate.GetRates:input_type -> rate.Request
	1, // 1: rate.Rate.GetRates:output_type -> rate.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rate_proto_init() }
func file_rate_proto_init() {
	if File_rate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rate_proto_rawDesc), len(file_rate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rate_proto_goTypes,
		DependencyIndexes: file_rate_proto_depIdxs,
		MessageInfos:      file_rate_proto_msgTypes,
	}.Build()
	File_rate_proto = out.File
	file_rate_proto_goTypes = nil
	file_rate_proto_depIdxs = nil
}
