// Code generated by protoc-gen-symphony. DO NOT EDIT.
package rate

import (
	"bytes"
	"encoding/binary"
)

func (m *Request) MarshalSymphony() ([]byte, error) {
	var buf bytes.Buffer
	// Layout header and field ordering
	buf.WriteByte(0x00) // layout header
	buf.Write([]byte{1, 2, 3})

	// Calculate offsets for variable-length fields
	offset := 0

	// Field 1 (HotelIds): repeated variable-length
	binary.Write(&buf, binary.LittleEndian, byte(1))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of HotelIds
	totalLen := 0
	for _, item := range m.HotelIds {
		totalLen += 4 + len(item) // 4 bytes for length + string data
	}
	binary.Write(&buf, binary.LittleEndian, uint16(totalLen))
	offset += totalLen
	// Field 2 (InDate): string
	binary.Write(&buf, binary.LittleEndian, byte(2))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of InDate
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.InDate)))
	offset += len(m.InDate)
	// Field 3 (OutDate): string
	binary.Write(&buf, binary.LittleEndian, byte(3))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of OutDate
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.OutDate)))
	offset += len(m.OutDate)

	// Write actual field data
	// Write repeated variable-length field HotelIds data
	for _, item := range m.HotelIds {
		binary.Write(&buf, binary.LittleEndian, uint32(len(item)))
		buf.Write([]byte(item))
	}
	// Write string field InDate
	buf.Write([]byte(m.InDate))
	// Write string field OutDate
	buf.Write([]byte(m.OutDate))

	return buf.Bytes(), nil
}

func (m *Request) UnmarshalSymphony(data []byte) error {
	// Parse header and field ordering
	reader := bytes.NewReader(data)
	var header byte
	if err := binary.Read(reader, binary.LittleEndian, &header); err != nil {
		return err
	}

	fieldOrder := make([]byte, 3)
	if _, err := reader.Read(fieldOrder); err != nil {
		return err
	}

	// Parse offset table for variable-length fields
	type offsetEntry struct{ offset, length uint16 }
	offsets := map[byte]offsetEntry{}
	for i := 0; i < 3; i++ {
		var fieldID byte
		var off, len uint16
		if err := binary.Read(reader, binary.LittleEndian, &fieldID); err != nil {
			return err
		}
		if err := binary.Read(reader, binary.LittleEndian, &off); err != nil {
			return err
		}
		if err := binary.Read(reader, binary.LittleEndian, &len); err != nil {
			return err
		}
		offsets[fieldID] = offsetEntry{off, len}
	}

	// Extract data region (everything after the offset table)
	dataRegion := data[len(data)-reader.Len():]

	// Unmarshal individual fields
	// Unmarshal repeated variable-length field HotelIds (field 1)
	if entry, ok := offsets[1]; ok {
		// Initialize slice
		m.HotelIds = make([]string, 0)
		// Read repeated field data
		dataStart := entry.offset
		dataEnd := entry.offset + entry.length

		// Handle empty repeated field case
		if dataEnd > dataStart {
			itemReader := bytes.NewReader(dataRegion[dataStart:dataEnd])
			bytesRead := uint16(0)
			for bytesRead < entry.length {
				var itemLen uint32
				if err := binary.Read(itemReader, binary.LittleEndian, &itemLen); err != nil {
					return err
				}
				bytesRead += 4 // length of uint32

				// Handle empty string case
				if itemLen == 0 {
					m.HotelIds = append(m.HotelIds, "")
					continue
				}

				itemData := make([]byte, itemLen)
				if _, err := itemReader.Read(itemData); err != nil {
					return err
				}
				bytesRead += uint16(itemLen)
				m.HotelIds = append(m.HotelIds, string(itemData))
			}
		}
	}
	// Unmarshal string field InDate (field 2)
	if entry, ok := offsets[2]; ok {
		m.InDate = string(dataRegion[entry.offset : entry.offset+entry.length])
	}
	// Unmarshal string field OutDate (field 3)
	if entry, ok := offsets[3]; ok {
		m.OutDate = string(dataRegion[entry.offset : entry.offset+entry.length])
	}

	return nil
}

func (m *Result) MarshalSymphony() ([]byte, error) {
	var buf bytes.Buffer
	// Layout header and field ordering
	buf.WriteByte(0x00) // layout header
	buf.Write([]byte{1, 2, 3, 4, 5, 6, 7, 8, 9})

	// Calculate offsets for variable-length fields
	offset := 0
	offset += 8 // BookableRate
	offset += 8 // TotalRate
	offset += 8 // TotalRateInclusive

	// Field 1 (HotelId): string
	binary.Write(&buf, binary.LittleEndian, byte(1))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of HotelId
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.HotelId)))
	offset += len(m.HotelId)
	// Field 2 (Code): string
	binary.Write(&buf, binary.LittleEndian, byte(2))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of Code
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.Code)))
	offset += len(m.Code)
	// Field 3 (InDate): string
	binary.Write(&buf, binary.LittleEndian, byte(3))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of InDate
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.InDate)))
	offset += len(m.InDate)
	// Field 4 (OutDate): string
	binary.Write(&buf, binary.LittleEndian, byte(4))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of OutDate
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.OutDate)))
	offset += len(m.OutDate)
	// Field 8 (Currency): string
	binary.Write(&buf, binary.LittleEndian, byte(8))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of Currency
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.Currency)))
	offset += len(m.Currency)
	// Field 9 (RoomDescription): string
	binary.Write(&buf, binary.LittleEndian, byte(9))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of RoomDescription
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.RoomDescription)))
	offset += len(m.RoomDescription)

	// Write actual field data
	// Write string field HotelId
	buf.Write([]byte(m.HotelId))
	// Write string field Code
	buf.Write([]byte(m.Code))
	// Write string field InDate
	buf.Write([]byte(m.InDate))
	// Write string field OutDate
	buf.Write([]byte(m.OutDate))
	// Write fixed field BookableRate
	binary.Write(&buf, binary.LittleEndian, m.BookableRate)
	// Write fixed field TotalRate
	binary.Write(&buf, binary.LittleEndian, m.TotalRate)
	// Write fixed field TotalRateInclusive
	binary.Write(&buf, binary.LittleEndian, m.TotalRateInclusive)
	// Write string field Currency
	buf.Write([]byte(m.Currency))
	// Write string field RoomDescription
	buf.Write([]byte(m.RoomDescription))

	return buf.Bytes(), nil
}

func (m *Result) UnmarshalSymphony(data []byte) error {
	// Parse header and field ordering
	reader := bytes.NewReader(data)
	var header byte
	if err := binary.Read(reader, binary.LittleEndian, &header); err != nil {
		return err
	}

	fieldOrder := make([]byte, 9)
	if _, err := reader.Read(fieldOrder); err != nil {
		return err
	}

	// Parse offset table for variable-length fields
	type offsetEntry struct{ offset, length uint16 }
	offsets := map[byte]offsetEntry{}
	for i := 0; i < 6; i++ {
		var fieldID byte
		var off, len uint16
		if err := binary.Read(reader, binary.LittleEndian, &fieldID); err != nil {
			return err
		}
		if err := binary.Read(reader, binary.LittleEndian, &off); err != nil {
			return err
		}
		if err := binary.Read(reader, binary.LittleEndian, &len); err != nil {
			return err
		}
		offsets[fieldID] = offsetEntry{off, len}
	}

	// Extract data region (everything after the offset table)
	dataRegion := data[len(data)-reader.Len():]

	// Unmarshal individual fields
	// Unmarshal string field HotelId (field 1)
	if entry, ok := offsets[1]; ok {
		m.HotelId = string(dataRegion[entry.offset : entry.offset+entry.length])
	}
	// Unmarshal string field Code (field 2)
	if entry, ok := offsets[2]; ok {
		m.Code = string(dataRegion[entry.offset : entry.offset+entry.length])
	}
	// Unmarshal string field InDate (field 3)
	if entry, ok := offsets[3]; ok {
		m.InDate = string(dataRegion[entry.offset : entry.offset+entry.length])
	}
	// Unmarshal string field OutDate (field 4)
	if entry, ok := offsets[4]; ok {
		m.OutDate = string(dataRegion[entry.offset : entry.offset+entry.length])
	}
	// Unmarshal fixed field BookableRate (field 5)
	if err := binary.Read(bytes.NewReader(dataRegion[0:8]), binary.LittleEndian, &m.BookableRate); err != nil {
		return err
	}
	// Unmarshal fixed field TotalRate (field 6)
	if err := binary.Read(bytes.NewReader(dataRegion[8:16]), binary.LittleEndian, &m.TotalRate); err != nil {
		return err
	}
	// Unmarshal fixed field TotalRateInclusive (field 7)
	if err := binary.Read(bytes.NewReader(dataRegion[16:24]), binary.LittleEndian, &m.TotalRateInclusive); err != nil {
		return err
	}
	// Unmarshal string field Currency (field 8)
	if entry, ok := offsets[8]; ok {
		m.Currency = string(dataRegion[entry.offset : entry.offset+entry.length])
	}
	// Unmarshal string field RoomDescription (field 9)
	if entry, ok := offsets[9]; ok {
		m.RoomDescription = string(dataRegion[entry.offset : entry.offset+entry.length])
	}

	return nil
}
