// Code generated by protoc-gen-arpc. DO NOT EDIT.
package rate

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
)

// RateClient is the client API for Rate service.
type RateClient interface {
	GetRates(ctx context.Context, req *Request) (*Result, error)
}

type arpcRateClient struct {
	client *rpc.Client
}

func NewRateClient(client *rpc.Client) RateClient {
	return &arpcRateClient{client: client}
}

func (c *arpcRateClient) GetRates(ctx context.Context, req *Request) (*Result, error) {
	resp := new(Result)
	if err := c.client.Call(ctx, "Rate", "GetRates", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type RateServer interface {
	GetRates(ctx context.Context, req *Request) (*Result, context.Context, error)
}

func RegisterRateServer(s *rpc.Server, srv RateServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Rate",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"GetRates": {
				MethodName: "GetRates",
				Handler:    _Rate_GetRates_Handler,
			},
		},
	}, srv)
}
func _Rate_GetRates_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(RateServer).GetRates(ctx, in)
	return out, newCtx, err
}
