// Code generated by protoc-gen-arpc. DO NOT EDIT.
package reservation

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
)

// ReservationClient is the client API for Reservation service.
type ReservationClient interface {
	MakeReservation(ctx context.Context, req *Request) (*Result, error)
	CheckAvailability(ctx context.Context, req *Request) (*Result, error)
}

type arpcReservationClient struct {
	client *rpc.Client
}

func NewReservationClient(client *rpc.Client) ReservationClient {
	return &arpcReservationClient{client: client}
}

func (c *arpcReservationClient) MakeReservation(ctx context.Context, req *Request) (*Result, error) {
	resp := new(Result)
	if err := c.client.Call(ctx, "Reservation", "MakeReservation", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *arpcReservationClient) CheckAvailability(ctx context.Context, req *Request) (*Result, error) {
	resp := new(Result)
	if err := c.client.Call(ctx, "Reservation", "CheckAvailability", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type ReservationServer interface {
	MakeReservation(ctx context.Context, req *Request) (*Result, context.Context, error)
	CheckAvailability(ctx context.Context, req *Request) (*Result, context.Context, error)
}

func RegisterReservationServer(s *rpc.Server, srv ReservationServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Reservation",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"MakeReservation": {
				MethodName: "MakeReservation",
				Handler:    _Reservation_MakeReservation_Handler,
			},
			"CheckAvailability": {
				MethodName: "CheckAvailability",
				Handler:    _Reservation_CheckAvailability_Handler,
			},
		},
	}, srv)
}
func _Reservation_MakeReservation_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(ReservationServer).MakeReservation(ctx, in)
	return out, newCtx, err
}
func _Reservation_CheckAvailability_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(ReservationServer).CheckAvailability(ctx, in)
	return out, newCtx, err
}
