// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CheckUserRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsCheckUserRequest(buf []byte, offset flatbuffers.UOffsetT) *CheckUserRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CheckUserRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CheckUserRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CheckUserRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CheckUserRequest) Username() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CheckUserRequest) Password() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CheckUserRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CheckUserRequestAddUsername(builder *flatbuffers.Builder, username flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(username), 0)
}
func CheckUserRequestAddPassword(builder *flatbuffers.Builder, password flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(password), 0)
}
func CheckUserRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
