// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CheckUserResult struct {
	_tab flatbuffers.Table
}

func GetRootAsCheckUserResult(buf []byte, offset flatbuffers.UOffsetT) *CheckUserResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CheckUserResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CheckUserResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CheckUserResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CheckUserResult) Correct() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *CheckUserResult) MutateCorrect(n bool) bool {
	return rcv._tab.MutateBoolSlot(4, n)
}

func CheckUserResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CheckUserResultAddCorrect(builder *flatbuffers.Builder, correct bool) {
	builder.PrependBoolSlot(0, correct, false)
}
func CheckUserResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
