// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetProfilesResult struct {
	_tab flatbuffers.Table
}

func GetRootAsGetProfilesResult(buf []byte, offset flatbuffers.UOffsetT) *GetProfilesResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetProfilesResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetProfilesResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetProfilesResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetProfilesResult) Hotels(obj *Hotel, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GetProfilesResult) HotelsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GetProfilesResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetProfilesResultAddHotels(builder *flatbuffers.Builder, hotels flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hotels), 0)
}
func GetProfilesResultStartHotelsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GetProfilesResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
