// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetProfilesRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetProfilesRequest(buf []byte, offset flatbuffers.UOffsetT) *GetProfilesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetProfilesRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetProfilesRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetProfilesRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetProfilesRequest) HotelIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *GetProfilesRequest) HotelIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GetProfilesRequest) Locale() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GetProfilesRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func GetProfilesRequestAddHotelIds(builder *flatbuffers.Builder, hotelIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hotelIds), 0)
}
func GetProfilesRequestStartHotelIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GetProfilesRequestAddLocale(builder *flatbuffers.Builder, locale flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(locale), 0)
}
func GetProfilesRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
