// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetRatesResult struct {
	_tab flatbuffers.Table
}

func GetRootAsGetRatesResult(buf []byte, offset flatbuffers.UOffsetT) *GetRatesResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetRatesResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetRatesResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetRatesResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetRatesResult) RatePlans(obj *RatePlan, j int) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		x := rcv._tab.Vector(o)
		x += flatbuffers.UOffsetT(j) * 4
		x = rcv._tab.Indirect(x)
		obj.Init(rcv._tab.Bytes, x)
		return true
	}
	return false
}

func (rcv *GetRatesResult) RatePlansLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func GetRatesResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func GetRatesResultAddRatePlans(builder *flatbuffers.Builder, ratePlans flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ratePlans), 0)
}
func GetRatesResultStartRatePlansVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GetRatesResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
