// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetRecommendationsRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetRecommendationsRequest(buf []byte, offset flatbuffers.UOffsetT) *GetRecommendationsRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetRecommendationsRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetRecommendationsRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetRecommendationsRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetRecommendationsRequest) Require() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GetRecommendationsRequest) Lat() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GetRecommendationsRequest) MutateLat(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *GetRecommendationsRequest) Lon() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *GetRecommendationsRequest) MutateLon(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func GetRecommendationsRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GetRecommendationsRequestAddRequire(builder *flatbuffers.Builder, require flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(require), 0)
}
func GetRecommendationsRequestAddLat(builder *flatbuffers.Builder, lat float64) {
	builder.PrependFloat64Slot(1, lat, 0.0)
}
func GetRecommendationsRequestAddLon(builder *flatbuffers.Builder, lon float64) {
	builder.PrependFloat64Slot(2, lon, 0.0)
}
func GetRecommendationsRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
