// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type GetRatesRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsGetRatesRequest(buf []byte, offset flatbuffers.UOffsetT) *GetRatesRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &GetRatesRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *GetRatesRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *GetRatesRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *GetRatesRequest) HotelIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *GetRatesRequest) HotelIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *GetRatesRequest) InDate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *GetRatesRequest) OutDate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func GetRatesRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func GetRatesRequestAddHotelIds(builder *flatbuffers.Builder, hotelIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hotelIds), 0)
}
func GetRatesRequestStartHotelIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func GetRatesRequestAddInDate(builder *flatbuffers.Builder, inDate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(inDate), 0)
}
func GetRatesRequestAddOutDate(builder *flatbuffers.Builder, outDate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(outDate), 0)
}
func GetRatesRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
