// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Image struct {
	_tab flatbuffers.Table
}

func GetRootAsImage(buf []byte, offset flatbuffers.UOffsetT) *Image {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Image{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *Image) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Image) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Image) Url() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Image) Default() bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetBool(o + rcv._tab.Pos)
	}
	return false
}

func (rcv *Image) MutateDefault(n bool) bool {
	return rcv._tab.MutateBoolSlot(6, n)
}

func ImageStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ImageAddUrl(builder *flatbuffers.Builder, url flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(url), 0)
}
func ImageAddDefault(builder *flatbuffers.Builder, default_ bool) {
	builder.PrependBoolSlot(1, default_, false)
}
func ImageEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
