// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NearbyRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsNearbyRequest(buf []byte, offset flatbuffers.UOffsetT) *NearbyRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NearbyRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NearbyRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NearbyRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NearbyRequest) Lat() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *NearbyRequest) MutateLat(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *NearbyRequest) Lon() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *NearbyRequest) MutateLon(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *NearbyRequest) Latstring() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func NearbyRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(3)
}
func NearbyRequestAddLat(builder *flatbuffers.Builder, lat float32) {
	builder.PrependFloat32Slot(0, lat, 0.0)
}
func NearbyRequestAddLon(builder *flatbuffers.Builder, lon float32) {
	builder.PrependFloat32Slot(1, lon, 0.0)
}
func NearbyRequestAddLatstring(builder *flatbuffers.Builder, latstring flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(latstring), 0)
}
func NearbyRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
