// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type NearbyResult struct {
	_tab flatbuffers.Table
}

func GetRootAsNearbyResult(buf []byte, offset flatbuffers.UOffsetT) *NearbyResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &NearbyResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *NearbyResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *NearbyResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *NearbyResult) HotelIds(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *NearbyResult) HotelIdsLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func NearbyResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func NearbyResultAddHotelIds(builder *flatbuffers.Builder, hotelIds flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hotelIds), 0)
}
func NearbyResultStartHotelIdsVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func NearbyResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
