// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RatePlan struct {
	_tab flatbuffers.Table
}

func GetRootAsRatePlan(buf []byte, offset flatbuffers.UOffsetT) *RatePlan {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RatePlan{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RatePlan) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RatePlan) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RatePlan) HotelId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RatePlan) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RatePlan) InDate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RatePlan) OutDate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RatePlan) RoomType(obj *RoomType) *RoomType {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		x := rcv._tab.Indirect(o + rcv._tab.Pos)
		if obj == nil {
			obj = new(RoomType)
		}
		obj.Init(rcv._tab.Bytes, x)
		return obj
	}
	return nil
}

func RatePlanStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func RatePlanAddHotelId(builder *flatbuffers.Builder, hotelId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hotelId), 0)
}
func RatePlanAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(code), 0)
}
func RatePlanAddInDate(builder *flatbuffers.Builder, inDate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(inDate), 0)
}
func RatePlanAddOutDate(builder *flatbuffers.Builder, outDate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(outDate), 0)
}
func RatePlanAddRoomType(builder *flatbuffers.Builder, roomType flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(roomType), 0)
}
func RatePlanEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
