// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReservationResult struct {
	_tab flatbuffers.Table
}

func GetRootAsReservationResult(buf []byte, offset flatbuffers.UOffsetT) *ReservationResult {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReservationResult{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ReservationResult) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReservationResult) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReservationResult) HotelId(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *ReservationResult) HotelIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func ReservationResultStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func ReservationResultAddHotelId(builder *flatbuffers.Builder, hotelId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(hotelId), 0)
}
func ReservationResultStartHotelIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ReservationResultEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
