// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ReservationRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsReservationRequest(buf []byte, offset flatbuffers.UOffsetT) *ReservationRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ReservationRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *ReservationRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ReservationRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ReservationRequest) CustomerName() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ReservationRequest) HotelId(j int) []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.ByteVector(a + flatbuffers.UOffsetT(j*4))
	}
	return nil
}

func (rcv *ReservationRequest) HotelIdLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *ReservationRequest) InDate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ReservationRequest) OutDate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *ReservationRequest) RoomNumber() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *ReservationRequest) MutateRoomNumber(n int32) bool {
	return rcv._tab.MutateInt32Slot(12, n)
}

func ReservationRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(5)
}
func ReservationRequestAddCustomerName(builder *flatbuffers.Builder, customerName flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(customerName), 0)
}
func ReservationRequestAddHotelId(builder *flatbuffers.Builder, hotelId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(hotelId), 0)
}
func ReservationRequestStartHotelIdVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(4, numElems, 4)
}
func ReservationRequestAddInDate(builder *flatbuffers.Builder, inDate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(inDate), 0)
}
func ReservationRequestAddOutDate(builder *flatbuffers.Builder, outDate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(outDate), 0)
}
func ReservationRequestAddRoomNumber(builder *flatbuffers.Builder, roomNumber int32) {
	builder.PrependInt32Slot(4, roomNumber, 0)
}
func ReservationRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
