// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type RoomType struct {
	_tab flatbuffers.Table
}

func GetRootAsRoomType(buf []byte, offset flatbuffers.UOffsetT) *RoomType {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &RoomType{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *RoomType) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *RoomType) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *RoomType) BookableRate() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *RoomType) MutateBookableRate(n float64) bool {
	return rcv._tab.MutateFloat64Slot(4, n)
}

func (rcv *RoomType) TotalRate() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *RoomType) MutateTotalRate(n float64) bool {
	return rcv._tab.MutateFloat64Slot(6, n)
}

func (rcv *RoomType) TotalRateInclusive() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *RoomType) MutateTotalRateInclusive(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *RoomType) Code() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RoomType) Currency() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(12))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *RoomType) RoomDescription() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(14))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func RoomTypeStart(builder *flatbuffers.Builder) {
	builder.StartObject(6)
}
func RoomTypeAddBookableRate(builder *flatbuffers.Builder, bookableRate float64) {
	builder.PrependFloat64Slot(0, bookableRate, 0.0)
}
func RoomTypeAddTotalRate(builder *flatbuffers.Builder, totalRate float64) {
	builder.PrependFloat64Slot(1, totalRate, 0.0)
}
func RoomTypeAddTotalRateInclusive(builder *flatbuffers.Builder, totalRateInclusive float64) {
	builder.PrependFloat64Slot(2, totalRateInclusive, 0.0)
}
func RoomTypeAddCode(builder *flatbuffers.Builder, code flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(code), 0)
}
func RoomTypeAddCurrency(builder *flatbuffers.Builder, currency flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(4, flatbuffers.UOffsetT(currency), 0)
}
func RoomTypeAddRoomDescription(builder *flatbuffers.Builder, roomDescription flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(5, flatbuffers.UOffsetT(roomDescription), 0)
}
func RoomTypeEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
