// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package hotel_reservation

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type SearchRequest struct {
	_tab flatbuffers.Table
}

func GetRootAsSearchRequest(buf []byte, offset flatbuffers.UOffsetT) *SearchRequest {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &SearchRequest{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *SearchRequest) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *SearchRequest) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *SearchRequest) Lat() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *SearchRequest) MutateLat(n float32) bool {
	return rcv._tab.MutateFloat32Slot(4, n)
}

func (rcv *SearchRequest) Lon() float32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetFloat32(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *SearchRequest) MutateLon(n float32) bool {
	return rcv._tab.MutateFloat32Slot(6, n)
}

func (rcv *SearchRequest) InDate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *SearchRequest) OutDate() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func SearchRequestStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func SearchRequestAddLat(builder *flatbuffers.Builder, lat float32) {
	builder.PrependFloat32Slot(0, lat, 0.0)
}
func SearchRequestAddLon(builder *flatbuffers.Builder, lon float32) {
	builder.PrependFloat32Slot(1, lon, 0.0)
}
func SearchRequestAddInDate(builder *flatbuffers.Builder, inDate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(2, flatbuffers.UOffsetT(inDate), 0)
}
func SearchRequestAddOutDate(builder *flatbuffers.Builder, outDate flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(outDate), 0)
}
func SearchRequestEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
