// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: hotel_reservation.proto

package hotel_reservation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The latitude and longitude of the current location.
type NearbyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	Latstring     string                 `protobuf:"bytes,3,opt,name=latstring,proto3" json:"latstring,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyRequest) Reset() {
	*x = NearbyRequest{}
	mi := &file_hotel_reservation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyRequest) ProtoMessage() {}

func (x *NearbyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyRequest.ProtoReflect.Descriptor instead.
func (*NearbyRequest) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{0}
}

func (x *NearbyRequest) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *NearbyRequest) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *NearbyRequest) GetLatstring() string {
	if x != nil {
		return x.Latstring
	}
	return ""
}

type NearbyResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelIds      []string               `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NearbyResult) Reset() {
	*x = NearbyResult{}
	mi := &file_hotel_reservation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NearbyResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NearbyResult) ProtoMessage() {}

func (x *NearbyResult) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NearbyResult.ProtoReflect.Descriptor instead.
func (*NearbyResult) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{1}
}

func (x *NearbyResult) GetHotelIds() []string {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

type GetProfilesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelIds      []string               `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	Locale        string                 `protobuf:"bytes,2,opt,name=locale,proto3" json:"locale,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesRequest) Reset() {
	*x = GetProfilesRequest{}
	mi := &file_hotel_reservation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesRequest) ProtoMessage() {}

func (x *GetProfilesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesRequest.ProtoReflect.Descriptor instead.
func (*GetProfilesRequest) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{2}
}

func (x *GetProfilesRequest) GetHotelIds() []string {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

func (x *GetProfilesRequest) GetLocale() string {
	if x != nil {
		return x.Locale
	}
	return ""
}

type GetProfilesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hotels        []*Hotel               `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProfilesResult) Reset() {
	*x = GetProfilesResult{}
	mi := &file_hotel_reservation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProfilesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProfilesResult) ProtoMessage() {}

func (x *GetProfilesResult) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProfilesResult.ProtoReflect.Descriptor instead.
func (*GetProfilesResult) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{3}
}

func (x *GetProfilesResult) GetHotels() []*Hotel {
	if x != nil {
		return x.Hotels
	}
	return nil
}

type Hotel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber   string                 `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Address       *Address               `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Images        []*Image               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hotel) Reset() {
	*x = Hotel{}
	mi := &file_hotel_reservation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hotel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hotel) ProtoMessage() {}

func (x *Hotel) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hotel.ProtoReflect.Descriptor instead.
func (*Hotel) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{4}
}

func (x *Hotel) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Hotel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Hotel) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *Hotel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Hotel) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *Hotel) GetImages() []*Image {
	if x != nil {
		return x.Images
	}
	return nil
}

type Address struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreetNumber  string                 `protobuf:"bytes,1,opt,name=streetNumber,proto3" json:"streetNumber,omitempty"`
	StreetName    string                 `protobuf:"bytes,2,opt,name=streetName,proto3" json:"streetName,omitempty"`
	City          string                 `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State         string                 `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	Country       string                 `protobuf:"bytes,5,opt,name=country,proto3" json:"country,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	Lat           float32                `protobuf:"fixed32,7,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,8,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Address) Reset() {
	*x = Address{}
	mi := &file_hotel_reservation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{5}
}

func (x *Address) GetStreetNumber() string {
	if x != nil {
		return x.StreetNumber
	}
	return ""
}

func (x *Address) GetStreetName() string {
	if x != nil {
		return x.StreetName
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *Address) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type Image struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Default       bool                   `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_hotel_reservation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{6}
}

func (x *Image) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Image) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

// The requirement of the recommendation.
type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Require       string                 `protobuf:"bytes,1,opt,name=require,proto3" json:"require,omitempty"`
	Lat           float64                `protobuf:"fixed64,2,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float64                `protobuf:"fixed64,3,opt,name=lon,proto3" json:"lon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_hotel_reservation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{7}
}

func (x *GetRecommendationsRequest) GetRequire() string {
	if x != nil {
		return x.Require
	}
	return ""
}

func (x *GetRecommendationsRequest) GetLat() float64 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *GetRecommendationsRequest) GetLon() float64 {
	if x != nil {
		return x.Lon
	}
	return 0
}

type GetRecommendationsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelIds      []string               `protobuf:"bytes,1,rep,name=HotelIds,proto3" json:"HotelIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsResult) Reset() {
	*x = GetRecommendationsResult{}
	mi := &file_hotel_reservation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResult) ProtoMessage() {}

func (x *GetRecommendationsResult) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResult.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResult) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{8}
}

func (x *GetRecommendationsResult) GetHotelIds() []string {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

type GetRatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelIds      []string               `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	InDate        string                 `protobuf:"bytes,2,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate       string                 `protobuf:"bytes,3,opt,name=outDate,proto3" json:"outDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesRequest) Reset() {
	*x = GetRatesRequest{}
	mi := &file_hotel_reservation_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesRequest) ProtoMessage() {}

func (x *GetRatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesRequest.ProtoReflect.Descriptor instead.
func (*GetRatesRequest) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{9}
}

func (x *GetRatesRequest) GetHotelIds() []string {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

func (x *GetRatesRequest) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *GetRatesRequest) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

type GetRatesResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RatePlans     []*RatePlan            `protobuf:"bytes,1,rep,name=ratePlans,proto3" json:"ratePlans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRatesResult) Reset() {
	*x = GetRatesResult{}
	mi := &file_hotel_reservation_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRatesResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRatesResult) ProtoMessage() {}

func (x *GetRatesResult) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRatesResult.ProtoReflect.Descriptor instead.
func (*GetRatesResult) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{10}
}

func (x *GetRatesResult) GetRatePlans() []*RatePlan {
	if x != nil {
		return x.RatePlans
	}
	return nil
}

type RatePlan struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelId       string                 `protobuf:"bytes,1,opt,name=hotelId,proto3" json:"hotelId,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	InDate        string                 `protobuf:"bytes,3,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate       string                 `protobuf:"bytes,4,opt,name=outDate,proto3" json:"outDate,omitempty"`
	RoomType      *RoomType              `protobuf:"bytes,5,opt,name=roomType,proto3" json:"roomType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RatePlan) Reset() {
	*x = RatePlan{}
	mi := &file_hotel_reservation_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RatePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RatePlan) ProtoMessage() {}

func (x *RatePlan) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RatePlan.ProtoReflect.Descriptor instead.
func (*RatePlan) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{11}
}

func (x *RatePlan) GetHotelId() string {
	if x != nil {
		return x.HotelId
	}
	return ""
}

func (x *RatePlan) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RatePlan) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *RatePlan) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

func (x *RatePlan) GetRoomType() *RoomType {
	if x != nil {
		return x.RoomType
	}
	return nil
}

type RoomType struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BookableRate       float64                `protobuf:"fixed64,1,opt,name=bookableRate,proto3" json:"bookableRate,omitempty"`
	TotalRate          float64                `protobuf:"fixed64,2,opt,name=totalRate,proto3" json:"totalRate,omitempty"`
	TotalRateInclusive float64                `protobuf:"fixed64,3,opt,name=totalRateInclusive,proto3" json:"totalRateInclusive,omitempty"`
	Code               string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Currency           string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	RoomDescription    string                 `protobuf:"bytes,6,opt,name=roomDescription,proto3" json:"roomDescription,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RoomType) Reset() {
	*x = RoomType{}
	mi := &file_hotel_reservation_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomType) ProtoMessage() {}

func (x *RoomType) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomType.ProtoReflect.Descriptor instead.
func (*RoomType) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{12}
}

func (x *RoomType) GetBookableRate() float64 {
	if x != nil {
		return x.BookableRate
	}
	return 0
}

func (x *RoomType) GetTotalRate() float64 {
	if x != nil {
		return x.TotalRate
	}
	return 0
}

func (x *RoomType) GetTotalRateInclusive() float64 {
	if x != nil {
		return x.TotalRateInclusive
	}
	return 0
}

func (x *RoomType) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *RoomType) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *RoomType) GetRoomDescription() string {
	if x != nil {
		return x.RoomDescription
	}
	return ""
}

type ReservationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerName  string                 `protobuf:"bytes,1,opt,name=customerName,proto3" json:"customerName,omitempty"`
	HotelId       []string               `protobuf:"bytes,2,rep,name=hotelId,proto3" json:"hotelId,omitempty"`
	InDate        string                 `protobuf:"bytes,3,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate       string                 `protobuf:"bytes,4,opt,name=outDate,proto3" json:"outDate,omitempty"`
	RoomNumber    int32                  `protobuf:"varint,5,opt,name=roomNumber,proto3" json:"roomNumber,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationRequest) Reset() {
	*x = ReservationRequest{}
	mi := &file_hotel_reservation_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationRequest) ProtoMessage() {}

func (x *ReservationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationRequest.ProtoReflect.Descriptor instead.
func (*ReservationRequest) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{13}
}

func (x *ReservationRequest) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *ReservationRequest) GetHotelId() []string {
	if x != nil {
		return x.HotelId
	}
	return nil
}

func (x *ReservationRequest) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *ReservationRequest) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

func (x *ReservationRequest) GetRoomNumber() int32 {
	if x != nil {
		return x.RoomNumber
	}
	return 0
}

type ReservationResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelId       []string               `protobuf:"bytes,1,rep,name=hotelId,proto3" json:"hotelId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationResult) Reset() {
	*x = ReservationResult{}
	mi := &file_hotel_reservation_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationResult) ProtoMessage() {}

func (x *ReservationResult) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationResult.ProtoReflect.Descriptor instead.
func (*ReservationResult) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{14}
}

func (x *ReservationResult) GetHotelId() []string {
	if x != nil {
		return x.HotelId
	}
	return nil
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lat           float32                `protobuf:"fixed32,1,opt,name=lat,proto3" json:"lat,omitempty"`
	Lon           float32                `protobuf:"fixed32,2,opt,name=lon,proto3" json:"lon,omitempty"`
	InDate        string                 `protobuf:"bytes,3,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate       string                 `protobuf:"bytes,4,opt,name=outDate,proto3" json:"outDate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_hotel_reservation_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{15}
}

func (x *SearchRequest) GetLat() float32 {
	if x != nil {
		return x.Lat
	}
	return 0
}

func (x *SearchRequest) GetLon() float32 {
	if x != nil {
		return x.Lon
	}
	return 0
}

func (x *SearchRequest) GetInDate() string {
	if x != nil {
		return x.InDate
	}
	return ""
}

func (x *SearchRequest) GetOutDate() string {
	if x != nil {
		return x.OutDate
	}
	return ""
}

type SearchResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HotelIds      []string               `protobuf:"bytes,1,rep,name=hotelIds,proto3" json:"hotelIds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_hotel_reservation_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{16}
}

func (x *SearchResult) GetHotelIds() []string {
	if x != nil {
		return x.HotelIds
	}
	return nil
}

type CheckUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserRequest) Reset() {
	*x = CheckUserRequest{}
	mi := &file_hotel_reservation_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserRequest) ProtoMessage() {}

func (x *CheckUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserRequest.ProtoReflect.Descriptor instead.
func (*CheckUserRequest) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{17}
}

func (x *CheckUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CheckUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CheckUserResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Correct       bool                   `protobuf:"varint,1,opt,name=correct,proto3" json:"correct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckUserResult) Reset() {
	*x = CheckUserResult{}
	mi := &file_hotel_reservation_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckUserResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckUserResult) ProtoMessage() {}

func (x *CheckUserResult) ProtoReflect() protoreflect.Message {
	mi := &file_hotel_reservation_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckUserResult.ProtoReflect.Descriptor instead.
func (*CheckUserResult) Descriptor() ([]byte, []int) {
	return file_hotel_reservation_proto_rawDescGZIP(), []int{18}
}

func (x *CheckUserResult) GetCorrect() bool {
	if x != nil {
		return x.Correct
	}
	return false
}

var File_hotel_reservation_proto protoreflect.FileDescriptor

const file_hotel_reservation_proto_rawDesc = "" +
	"\n" +
	"\x17hotel_reservation.proto\x12\x11hotel_reservation\"Q\n" +
	"\rNearbyRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x02R\x03lon\x12\x1c\n" +
	"\tlatstring\x18\x03 \x01(\tR\tlatstring\"*\n" +
	"\fNearbyResult\x12\x1a\n" +
	"\bhotelIds\x18\x01 \x03(\tR\bhotelIds\"H\n" +
	"\x12GetProfilesRequest\x12\x1a\n" +
	"\bhotelIds\x18\x01 \x03(\tR\bhotelIds\x12\x16\n" +
	"\x06locale\x18\x02 \x01(\tR\x06locale\"E\n" +
	"\x11GetProfilesResult\x120\n" +
	"\x06hotels\x18\x01 \x03(\v2\x18.hotel_reservation.HotelR\x06hotels\"\xd7\x01\n" +
	"\x05Hotel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vphoneNumber\x18\x03 \x01(\tR\vphoneNumber\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x124\n" +
	"\aaddress\x18\x05 \x01(\v2\x1a.hotel_reservation.AddressR\aaddress\x120\n" +
	"\x06images\x18\x06 \x03(\v2\x18.hotel_reservation.ImageR\x06images\"\xd5\x01\n" +
	"\aAddress\x12\"\n" +
	"\fstreetNumber\x18\x01 \x01(\tR\fstreetNumber\x12\x1e\n" +
	"\n" +
	"streetName\x18\x02 \x01(\tR\n" +
	"streetName\x12\x12\n" +
	"\x04city\x18\x03 \x01(\tR\x04city\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x18\n" +
	"\acountry\x18\x05 \x01(\tR\acountry\x12\x1e\n" +
	"\n" +
	"postalCode\x18\x06 \x01(\tR\n" +
	"postalCode\x12\x10\n" +
	"\x03lat\x18\a \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\b \x01(\x02R\x03lon\"3\n" +
	"\x05Image\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x18\n" +
	"\adefault\x18\x02 \x01(\bR\adefault\"Y\n" +
	"\x19GetRecommendationsRequest\x12\x18\n" +
	"\arequire\x18\x01 \x01(\tR\arequire\x12\x10\n" +
	"\x03lat\x18\x02 \x01(\x01R\x03lat\x12\x10\n" +
	"\x03lon\x18\x03 \x01(\x01R\x03lon\"6\n" +
	"\x18GetRecommendationsResult\x12\x1a\n" +
	"\bHotelIds\x18\x01 \x03(\tR\bHotelIds\"_\n" +
	"\x0fGetRatesRequest\x12\x1a\n" +
	"\bhotelIds\x18\x01 \x03(\tR\bhotelIds\x12\x16\n" +
	"\x06inDate\x18\x02 \x01(\tR\x06inDate\x12\x18\n" +
	"\aoutDate\x18\x03 \x01(\tR\aoutDate\"K\n" +
	"\x0eGetRatesResult\x129\n" +
	"\tratePlans\x18\x01 \x03(\v2\x1b.hotel_reservation.RatePlanR\tratePlans\"\xa3\x01\n" +
	"\bRatePlan\x12\x18\n" +
	"\ahotelId\x18\x01 \x01(\tR\ahotelId\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x16\n" +
	"\x06inDate\x18\x03 \x01(\tR\x06inDate\x12\x18\n" +
	"\aoutDate\x18\x04 \x01(\tR\aoutDate\x127\n" +
	"\broomType\x18\x05 \x01(\v2\x1b.hotel_reservation.RoomTypeR\broomType\"\xd6\x01\n" +
	"\bRoomType\x12\"\n" +
	"\fbookableRate\x18\x01 \x01(\x01R\fbookableRate\x12\x1c\n" +
	"\ttotalRate\x18\x02 \x01(\x01R\ttotalRate\x12.\n" +
	"\x12totalRateInclusive\x18\x03 \x01(\x01R\x12totalRateInclusive\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12(\n" +
	"\x0froomDescription\x18\x06 \x01(\tR\x0froomDescription\"\xa4\x01\n" +
	"\x12ReservationRequest\x12\"\n" +
	"\fcustomerName\x18\x01 \x01(\tR\fcustomerName\x12\x18\n" +
	"\ahotelId\x18\x02 \x03(\tR\ahotelId\x12\x16\n" +
	"\x06inDate\x18\x03 \x01(\tR\x06inDate\x12\x18\n" +
	"\aoutDate\x18\x04 \x01(\tR\aoutDate\x12\x1e\n" +
	"\n" +
	"roomNumber\x18\x05 \x01(\x05R\n" +
	"roomNumber\"-\n" +
	"\x11ReservationResult\x12\x18\n" +
	"\ahotelId\x18\x01 \x03(\tR\ahotelId\"e\n" +
	"\rSearchRequest\x12\x10\n" +
	"\x03lat\x18\x01 \x01(\x02R\x03lat\x12\x10\n" +
	"\x03lon\x18\x02 \x01(\x02R\x03lon\x12\x16\n" +
	"\x06inDate\x18\x03 \x01(\tR\x06inDate\x12\x18\n" +
	"\aoutDate\x18\x04 \x01(\tR\aoutDate\"*\n" +
	"\fSearchResult\x12\x1a\n" +
	"\bhotelIds\x18\x01 \x03(\tR\bhotelIds\"J\n" +
	"\x10CheckUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"+\n" +
	"\x0fCheckUserResult\x12\x18\n" +
	"\acorrect\x18\x01 \x01(\bR\acorrect2U\n" +
	"\x03Geo\x12N\n" +
	"\tNearbyGeo\x12 .hotel_reservation.NearbyRequest\x1a\x1f.hotel_reservation.NearbyResult2e\n" +
	"\aProfile\x12Z\n" +
	"\vGetProfiles\x12%.hotel_reservation.GetProfilesRequest\x1a$.hotel_reservation.GetProfilesResult2\x81\x01\n" +
	"\x0eRecommendation\x12o\n" +
	"\x12GetRecommendations\x12,.hotel_reservation.GetRecommendationsRequest\x1a+.hotel_reservation.GetRecommendationsResult2Y\n" +
	"\x04Rate\x12Q\n" +
	"\bGetRates\x12\".hotel_reservation.GetRatesRequest\x1a!.hotel_reservation.GetRatesResult2\xcf\x01\n" +
	"\vReservation\x12^\n" +
	"\x0fMakeReservation\x12%.hotel_reservation.ReservationRequest\x1a$.hotel_reservation.ReservationResult\x12`\n" +
	"\x11CheckAvailability\x12%.hotel_reservation.ReservationRequest\x1a$.hotel_reservation.ReservationResult2U\n" +
	"\x06Search\x12K\n" +
	"\x06Nearby\x12 .hotel_reservation.SearchRequest\x1a\x1f.hotel_reservation.SearchResult2\\\n" +
	"\x04User\x12T\n" +
	"\tCheckUser\x12#.hotel_reservation.CheckUserRequest\x1a\".hotel_reservation.CheckUserResultB\x15Z\x13./hotel_reservationb\x06proto3"

var (
	file_hotel_reservation_proto_rawDescOnce sync.Once
	file_hotel_reservation_proto_rawDescData []byte
)

func file_hotel_reservation_proto_rawDescGZIP() []byte {
	file_hotel_reservation_proto_rawDescOnce.Do(func() {
		file_hotel_reservation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_hotel_reservation_proto_rawDesc), len(file_hotel_reservation_proto_rawDesc)))
	})
	return file_hotel_reservation_proto_rawDescData
}

var file_hotel_reservation_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_hotel_reservation_proto_goTypes = []any{
	(*NearbyRequest)(nil),             // 0: hotel_reservation.NearbyRequest
	(*NearbyResult)(nil),              // 1: hotel_reservation.NearbyResult
	(*GetProfilesRequest)(nil),        // 2: hotel_reservation.GetProfilesRequest
	(*GetProfilesResult)(nil),         // 3: hotel_reservation.GetProfilesResult
	(*Hotel)(nil),                     // 4: hotel_reservation.Hotel
	(*Address)(nil),                   // 5: hotel_reservation.Address
	(*Image)(nil),                     // 6: hotel_reservation.Image
	(*GetRecommendationsRequest)(nil), // 7: hotel_reservation.GetRecommendationsRequest
	(*GetRecommendationsResult)(nil),  // 8: hotel_reservation.GetRecommendationsResult
	(*GetRatesRequest)(nil),           // 9: hotel_reservation.GetRatesRequest
	(*GetRatesResult)(nil),            // 10: hotel_reservation.GetRatesResult
	(*RatePlan)(nil),                  // 11: hotel_reservation.RatePlan
	(*RoomType)(nil),                  // 12: hotel_reservation.RoomType
	(*ReservationRequest)(nil),        // 13: hotel_reservation.ReservationRequest
	(*ReservationResult)(nil),         // 14: hotel_reservation.ReservationResult
	(*SearchRequest)(nil),             // 15: hotel_reservation.SearchRequest
	(*SearchResult)(nil),              // 16: hotel_reservation.SearchResult
	(*CheckUserRequest)(nil),          // 17: hotel_reservation.CheckUserRequest
	(*CheckUserResult)(nil),           // 18: hotel_reservation.CheckUserResult
}
var file_hotel_reservation_proto_depIdxs = []int32{
	4,  // 0: hotel_reservation.GetProfilesResult.hotels:type_name -> hotel_reservation.Hotel
	5,  // 1: hotel_reservation.Hotel.address:type_name -> hotel_reservation.Address
	6,  // 2: hotel_reservation.Hotel.images:type_name -> hotel_reservation.Image
	11, // 3: hotel_reservation.GetRatesResult.ratePlans:type_name -> hotel_reservation.RatePlan
	12, // 4: hotel_reservation.RatePlan.roomType:type_name -> hotel_reservation.RoomType
	0,  // 5: hotel_reservation.Geo.NearbyGeo:input_type -> hotel_reservation.NearbyRequest
	2,  // 6: hotel_reservation.Profile.GetProfiles:input_type -> hotel_reservation.GetProfilesRequest
	7,  // 7: hotel_reservation.Recommendation.GetRecommendations:input_type -> hotel_reservation.GetRecommendationsRequest
	9,  // 8: hotel_reservation.Rate.GetRates:input_type -> hotel_reservation.GetRatesRequest
	13, // 9: hotel_reservation.Reservation.MakeReservation:input_type -> hotel_reservation.ReservationRequest
	13, // 10: hotel_reservation.Reservation.CheckAvailability:input_type -> hotel_reservation.ReservationRequest
	15, // 11: hotel_reservation.Search.Nearby:input_type -> hotel_reservation.SearchRequest
	17, // 12: hotel_reservation.User.CheckUser:input_type -> hotel_reservation.CheckUserRequest
	1,  // 13: hotel_reservation.Geo.NearbyGeo:output_type -> hotel_reservation.NearbyResult
	3,  // 14: hotel_reservation.Profile.GetProfiles:output_type -> hotel_reservation.GetProfilesResult
	8,  // 15: hotel_reservation.Recommendation.GetRecommendations:output_type -> hotel_reservation.GetRecommendationsResult
	10, // 16: hotel_reservation.Rate.GetRates:output_type -> hotel_reservation.GetRatesResult
	14, // 17: hotel_reservation.Reservation.MakeReservation:output_type -> hotel_reservation.ReservationResult
	14, // 18: hotel_reservation.Reservation.CheckAvailability:output_type -> hotel_reservation.ReservationResult
	16, // 19: hotel_reservation.Search.Nearby:output_type -> hotel_reservation.SearchResult
	18, // 20: hotel_reservation.User.CheckUser:output_type -> hotel_reservation.CheckUserResult
	13, // [13:21] is the sub-list for method output_type
	5,  // [5:13] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_hotel_reservation_proto_init() }
func file_hotel_reservation_proto_init() {
	if File_hotel_reservation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_hotel_reservation_proto_rawDesc), len(file_hotel_reservation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   7,
		},
		GoTypes:           file_hotel_reservation_proto_goTypes,
		DependencyIndexes: file_hotel_reservation_proto_depIdxs,
		MessageInfos:      file_hotel_reservation_proto_msgTypes,
	}.Build()
	File_hotel_reservation_proto = out.File
	file_hotel_reservation_proto_goTypes = nil
	file_hotel_reservation_proto_depIdxs = nil
}
