// Code generated by capnpc-go. DO NOT EDIT.

package capnp

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	math "math"
)

type NearbyRequest capnp.Struct

// NearbyRequest_TypeID is the unique identifier for the type NearbyRequest.
const NearbyRequest_TypeID = 0xaaa492b3cdb32829

func NewNearbyRequest(s *capnp.Segment) (NearbyRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return NearbyRequest(st), err
}

func NewRootNearbyRequest(s *capnp.Segment) (NearbyRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return NearbyRequest(st), err
}

func ReadRootNearbyRequest(msg *capnp.Message) (NearbyRequest, error) {
	root, err := msg.Root()
	return NearbyRequest(root.Struct()), err
}

func (s NearbyRequest) String() string {
	str, _ := text.Marshal(0xaaa492b3cdb32829, capnp.Struct(s))
	return str
}

func (s NearbyRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (NearbyRequest) DecodeFromPtr(p capnp.Ptr) NearbyRequest {
	return NearbyRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s NearbyRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s NearbyRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s NearbyRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s NearbyRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s NearbyRequest) Lat() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s NearbyRequest) SetLat(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s NearbyRequest) Lon() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s NearbyRequest) SetLon(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s NearbyRequest) Latstring() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s NearbyRequest) HasLatstring() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s NearbyRequest) LatstringBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s NearbyRequest) SetLatstring(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

// NearbyRequest_List is a list of NearbyRequest.
type NearbyRequest_List = capnp.StructList[NearbyRequest]

// NewNearbyRequest creates a new list of NearbyRequest.
func NewNearbyRequest_List(s *capnp.Segment, sz int32) (NearbyRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[NearbyRequest](l), err
}

// NearbyRequest_Future is a wrapper for a NearbyRequest promised by a client call.
type NearbyRequest_Future struct{ *capnp.Future }

func (f NearbyRequest_Future) Struct() (NearbyRequest, error) {
	p, err := f.Future.Ptr()
	return NearbyRequest(p.Struct()), err
}

type NearbyResult capnp.Struct

// NearbyResult_TypeID is the unique identifier for the type NearbyResult.
const NearbyResult_TypeID = 0xd60e02d06047c143

func NewNearbyResult(s *capnp.Segment) (NearbyResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return NearbyResult(st), err
}

func NewRootNearbyResult(s *capnp.Segment) (NearbyResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return NearbyResult(st), err
}

func ReadRootNearbyResult(msg *capnp.Message) (NearbyResult, error) {
	root, err := msg.Root()
	return NearbyResult(root.Struct()), err
}

func (s NearbyResult) String() string {
	str, _ := text.Marshal(0xd60e02d06047c143, capnp.Struct(s))
	return str
}

func (s NearbyResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (NearbyResult) DecodeFromPtr(p capnp.Ptr) NearbyResult {
	return NearbyResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s NearbyResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s NearbyResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s NearbyResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s NearbyResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s NearbyResult) HotelIds() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s NearbyResult) HasHotelIds() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s NearbyResult) SetHotelIds(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewHotelIds sets the hotelIds field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s NearbyResult) NewHotelIds(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// NearbyResult_List is a list of NearbyResult.
type NearbyResult_List = capnp.StructList[NearbyResult]

// NewNearbyResult creates a new list of NearbyResult.
func NewNearbyResult_List(s *capnp.Segment, sz int32) (NearbyResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[NearbyResult](l), err
}

// NearbyResult_Future is a wrapper for a NearbyResult promised by a client call.
type NearbyResult_Future struct{ *capnp.Future }

func (f NearbyResult_Future) Struct() (NearbyResult, error) {
	p, err := f.Future.Ptr()
	return NearbyResult(p.Struct()), err
}

type GetProfilesRequest capnp.Struct

// GetProfilesRequest_TypeID is the unique identifier for the type GetProfilesRequest.
const GetProfilesRequest_TypeID = 0xd8ae42919638a537

func NewGetProfilesRequest(s *capnp.Segment) (GetProfilesRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return GetProfilesRequest(st), err
}

func NewRootGetProfilesRequest(s *capnp.Segment) (GetProfilesRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return GetProfilesRequest(st), err
}

func ReadRootGetProfilesRequest(msg *capnp.Message) (GetProfilesRequest, error) {
	root, err := msg.Root()
	return GetProfilesRequest(root.Struct()), err
}

func (s GetProfilesRequest) String() string {
	str, _ := text.Marshal(0xd8ae42919638a537, capnp.Struct(s))
	return str
}

func (s GetProfilesRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetProfilesRequest) DecodeFromPtr(p capnp.Ptr) GetProfilesRequest {
	return GetProfilesRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetProfilesRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GetProfilesRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetProfilesRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetProfilesRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GetProfilesRequest) HotelIds() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s GetProfilesRequest) HasHotelIds() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetProfilesRequest) SetHotelIds(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewHotelIds sets the hotelIds field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s GetProfilesRequest) NewHotelIds(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s GetProfilesRequest) Locale() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s GetProfilesRequest) HasLocale() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s GetProfilesRequest) LocaleBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s GetProfilesRequest) SetLocale(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// GetProfilesRequest_List is a list of GetProfilesRequest.
type GetProfilesRequest_List = capnp.StructList[GetProfilesRequest]

// NewGetProfilesRequest creates a new list of GetProfilesRequest.
func NewGetProfilesRequest_List(s *capnp.Segment, sz int32) (GetProfilesRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[GetProfilesRequest](l), err
}

// GetProfilesRequest_Future is a wrapper for a GetProfilesRequest promised by a client call.
type GetProfilesRequest_Future struct{ *capnp.Future }

func (f GetProfilesRequest_Future) Struct() (GetProfilesRequest, error) {
	p, err := f.Future.Ptr()
	return GetProfilesRequest(p.Struct()), err
}

type GetProfilesResult capnp.Struct

// GetProfilesResult_TypeID is the unique identifier for the type GetProfilesResult.
const GetProfilesResult_TypeID = 0xfbc204e12ed993c0

func NewGetProfilesResult(s *capnp.Segment) (GetProfilesResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetProfilesResult(st), err
}

func NewRootGetProfilesResult(s *capnp.Segment) (GetProfilesResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetProfilesResult(st), err
}

func ReadRootGetProfilesResult(msg *capnp.Message) (GetProfilesResult, error) {
	root, err := msg.Root()
	return GetProfilesResult(root.Struct()), err
}

func (s GetProfilesResult) String() string {
	str, _ := text.Marshal(0xfbc204e12ed993c0, capnp.Struct(s))
	return str
}

func (s GetProfilesResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetProfilesResult) DecodeFromPtr(p capnp.Ptr) GetProfilesResult {
	return GetProfilesResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetProfilesResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GetProfilesResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetProfilesResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetProfilesResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GetProfilesResult) Hotels() (Hotel_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return Hotel_List(p.List()), err
}

func (s GetProfilesResult) HasHotels() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetProfilesResult) SetHotels(v Hotel_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewHotels sets the hotels field to a newly
// allocated Hotel_List, preferring placement in s's segment.
func (s GetProfilesResult) NewHotels(n int32) (Hotel_List, error) {
	l, err := NewHotel_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Hotel_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// GetProfilesResult_List is a list of GetProfilesResult.
type GetProfilesResult_List = capnp.StructList[GetProfilesResult]

// NewGetProfilesResult creates a new list of GetProfilesResult.
func NewGetProfilesResult_List(s *capnp.Segment, sz int32) (GetProfilesResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GetProfilesResult](l), err
}

// GetProfilesResult_Future is a wrapper for a GetProfilesResult promised by a client call.
type GetProfilesResult_Future struct{ *capnp.Future }

func (f GetProfilesResult_Future) Struct() (GetProfilesResult, error) {
	p, err := f.Future.Ptr()
	return GetProfilesResult(p.Struct()), err
}

type Hotel capnp.Struct

// Hotel_TypeID is the unique identifier for the type Hotel.
const Hotel_TypeID = 0xceba325eebc749d9

func NewHotel(s *capnp.Segment) (Hotel, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6})
	return Hotel(st), err
}

func NewRootHotel(s *capnp.Segment) (Hotel, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6})
	return Hotel(st), err
}

func ReadRootHotel(msg *capnp.Message) (Hotel, error) {
	root, err := msg.Root()
	return Hotel(root.Struct()), err
}

func (s Hotel) String() string {
	str, _ := text.Marshal(0xceba325eebc749d9, capnp.Struct(s))
	return str
}

func (s Hotel) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Hotel) DecodeFromPtr(p capnp.Ptr) Hotel {
	return Hotel(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Hotel) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Hotel) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Hotel) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Hotel) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Hotel) Id() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Hotel) HasId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Hotel) IdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Hotel) SetId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Hotel) Name() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Hotel) HasName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Hotel) NameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Hotel) SetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Hotel) PhoneNumber() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Hotel) HasPhoneNumber() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Hotel) PhoneNumberBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Hotel) SetPhoneNumber(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Hotel) Description() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Hotel) HasDescription() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Hotel) DescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Hotel) SetDescription(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Hotel) Address() (Address, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return Address(p.Struct()), err
}

func (s Hotel) HasAddress() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Hotel) SetAddress(v Address) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewAddress sets the address field to a newly
// allocated Address struct, preferring placement in s's segment.
func (s Hotel) NewAddress() (Address, error) {
	ss, err := NewAddress(capnp.Struct(s).Segment())
	if err != nil {
		return Address{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Hotel) Images() (Image_List, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return Image_List(p.List()), err
}

func (s Hotel) HasImages() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Hotel) SetImages(v Image_List) error {
	return capnp.Struct(s).SetPtr(5, v.ToPtr())
}

// NewImages sets the images field to a newly
// allocated Image_List, preferring placement in s's segment.
func (s Hotel) NewImages(n int32) (Image_List, error) {
	l, err := NewImage_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return Image_List{}, err
	}
	err = capnp.Struct(s).SetPtr(5, l.ToPtr())
	return l, err
}

// Hotel_List is a list of Hotel.
type Hotel_List = capnp.StructList[Hotel]

// NewHotel creates a new list of Hotel.
func NewHotel_List(s *capnp.Segment, sz int32) (Hotel_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 6}, sz)
	return capnp.StructList[Hotel](l), err
}

// Hotel_Future is a wrapper for a Hotel promised by a client call.
type Hotel_Future struct{ *capnp.Future }

func (f Hotel_Future) Struct() (Hotel, error) {
	p, err := f.Future.Ptr()
	return Hotel(p.Struct()), err
}
func (p Hotel_Future) Address() Address_Future {
	return Address_Future{Future: p.Future.Field(4, nil)}
}

type Address capnp.Struct

// Address_TypeID is the unique identifier for the type Address.
const Address_TypeID = 0xb27b3e87e909de3f

func NewAddress(s *capnp.Segment) (Address, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return Address(st), err
}

func NewRootAddress(s *capnp.Segment) (Address, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6})
	return Address(st), err
}

func ReadRootAddress(msg *capnp.Message) (Address, error) {
	root, err := msg.Root()
	return Address(root.Struct()), err
}

func (s Address) String() string {
	str, _ := text.Marshal(0xb27b3e87e909de3f, capnp.Struct(s))
	return str
}

func (s Address) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Address) DecodeFromPtr(p capnp.Ptr) Address {
	return Address(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Address) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Address) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Address) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Address) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Address) StreetNumber() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Address) HasStreetNumber() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Address) StreetNumberBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Address) SetStreetNumber(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Address) StreetName() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Address) HasStreetName() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Address) StreetNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Address) SetStreetName(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Address) City() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Address) HasCity() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Address) CityBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Address) SetCity(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s Address) State() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s Address) HasState() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s Address) StateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s Address) SetState(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s Address) Country() (string, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.Text(), err
}

func (s Address) HasCountry() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s Address) CountryBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return p.TextBytes(), err
}

func (s Address) SetCountry(v string) error {
	return capnp.Struct(s).SetText(4, v)
}

func (s Address) PostalCode() (string, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.Text(), err
}

func (s Address) HasPostalCode() bool {
	return capnp.Struct(s).HasPtr(5)
}

func (s Address) PostalCodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(5)
	return p.TextBytes(), err
}

func (s Address) SetPostalCode(v string) error {
	return capnp.Struct(s).SetText(5, v)
}

func (s Address) Lat() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s Address) SetLat(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s Address) Lon() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s Address) SetLon(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

// Address_List is a list of Address.
type Address_List = capnp.StructList[Address]

// NewAddress creates a new list of Address.
func NewAddress_List(s *capnp.Segment, sz int32) (Address_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 6}, sz)
	return capnp.StructList[Address](l), err
}

// Address_Future is a wrapper for a Address promised by a client call.
type Address_Future struct{ *capnp.Future }

func (f Address_Future) Struct() (Address, error) {
	p, err := f.Future.Ptr()
	return Address(p.Struct()), err
}

type Image capnp.Struct

// Image_TypeID is the unique identifier for the type Image.
const Image_TypeID = 0xa1af556d19eb4715

func NewImage(s *capnp.Segment) (Image, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Image(st), err
}

func NewRootImage(s *capnp.Segment) (Image, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Image(st), err
}

func ReadRootImage(msg *capnp.Message) (Image, error) {
	root, err := msg.Root()
	return Image(root.Struct()), err
}

func (s Image) String() string {
	str, _ := text.Marshal(0xa1af556d19eb4715, capnp.Struct(s))
	return str
}

func (s Image) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Image) DecodeFromPtr(p capnp.Ptr) Image {
	return Image(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Image) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Image) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Image) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Image) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Image) Url() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s Image) HasUrl() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Image) UrlBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s Image) SetUrl(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s Image) Default() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Image) SetDefault(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// Image_List is a list of Image.
type Image_List = capnp.StructList[Image]

// NewImage creates a new list of Image.
func NewImage_List(s *capnp.Segment, sz int32) (Image_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Image](l), err
}

// Image_Future is a wrapper for a Image promised by a client call.
type Image_Future struct{ *capnp.Future }

func (f Image_Future) Struct() (Image, error) {
	p, err := f.Future.Ptr()
	return Image(p.Struct()), err
}

type GetRecommendationsRequest capnp.Struct

// GetRecommendationsRequest_TypeID is the unique identifier for the type GetRecommendationsRequest.
const GetRecommendationsRequest_TypeID = 0xb4f77962a677fe1b

func NewGetRecommendationsRequest(s *capnp.Segment) (GetRecommendationsRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return GetRecommendationsRequest(st), err
}

func NewRootGetRecommendationsRequest(s *capnp.Segment) (GetRecommendationsRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1})
	return GetRecommendationsRequest(st), err
}

func ReadRootGetRecommendationsRequest(msg *capnp.Message) (GetRecommendationsRequest, error) {
	root, err := msg.Root()
	return GetRecommendationsRequest(root.Struct()), err
}

func (s GetRecommendationsRequest) String() string {
	str, _ := text.Marshal(0xb4f77962a677fe1b, capnp.Struct(s))
	return str
}

func (s GetRecommendationsRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetRecommendationsRequest) DecodeFromPtr(p capnp.Ptr) GetRecommendationsRequest {
	return GetRecommendationsRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetRecommendationsRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GetRecommendationsRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetRecommendationsRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetRecommendationsRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GetRecommendationsRequest) Require() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s GetRecommendationsRequest) HasRequire() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetRecommendationsRequest) RequireBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s GetRecommendationsRequest) SetRequire(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s GetRecommendationsRequest) Lat() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s GetRecommendationsRequest) SetLat(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s GetRecommendationsRequest) Lon() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s GetRecommendationsRequest) SetLon(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

// GetRecommendationsRequest_List is a list of GetRecommendationsRequest.
type GetRecommendationsRequest_List = capnp.StructList[GetRecommendationsRequest]

// NewGetRecommendationsRequest creates a new list of GetRecommendationsRequest.
func NewGetRecommendationsRequest_List(s *capnp.Segment, sz int32) (GetRecommendationsRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 16, PointerCount: 1}, sz)
	return capnp.StructList[GetRecommendationsRequest](l), err
}

// GetRecommendationsRequest_Future is a wrapper for a GetRecommendationsRequest promised by a client call.
type GetRecommendationsRequest_Future struct{ *capnp.Future }

func (f GetRecommendationsRequest_Future) Struct() (GetRecommendationsRequest, error) {
	p, err := f.Future.Ptr()
	return GetRecommendationsRequest(p.Struct()), err
}

type GetRecommendationsResult capnp.Struct

// GetRecommendationsResult_TypeID is the unique identifier for the type GetRecommendationsResult.
const GetRecommendationsResult_TypeID = 0x90abad741d49aa10

func NewGetRecommendationsResult(s *capnp.Segment) (GetRecommendationsResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetRecommendationsResult(st), err
}

func NewRootGetRecommendationsResult(s *capnp.Segment) (GetRecommendationsResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetRecommendationsResult(st), err
}

func ReadRootGetRecommendationsResult(msg *capnp.Message) (GetRecommendationsResult, error) {
	root, err := msg.Root()
	return GetRecommendationsResult(root.Struct()), err
}

func (s GetRecommendationsResult) String() string {
	str, _ := text.Marshal(0x90abad741d49aa10, capnp.Struct(s))
	return str
}

func (s GetRecommendationsResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetRecommendationsResult) DecodeFromPtr(p capnp.Ptr) GetRecommendationsResult {
	return GetRecommendationsResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetRecommendationsResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GetRecommendationsResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetRecommendationsResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetRecommendationsResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GetRecommendationsResult) HotelIds() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s GetRecommendationsResult) HasHotelIds() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetRecommendationsResult) SetHotelIds(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewHotelIds sets the hotelIds field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s GetRecommendationsResult) NewHotelIds(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// GetRecommendationsResult_List is a list of GetRecommendationsResult.
type GetRecommendationsResult_List = capnp.StructList[GetRecommendationsResult]

// NewGetRecommendationsResult creates a new list of GetRecommendationsResult.
func NewGetRecommendationsResult_List(s *capnp.Segment, sz int32) (GetRecommendationsResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GetRecommendationsResult](l), err
}

// GetRecommendationsResult_Future is a wrapper for a GetRecommendationsResult promised by a client call.
type GetRecommendationsResult_Future struct{ *capnp.Future }

func (f GetRecommendationsResult_Future) Struct() (GetRecommendationsResult, error) {
	p, err := f.Future.Ptr()
	return GetRecommendationsResult(p.Struct()), err
}

type GetRatesRequest capnp.Struct

// GetRatesRequest_TypeID is the unique identifier for the type GetRatesRequest.
const GetRatesRequest_TypeID = 0xacd4e4ca3937ac30

func NewGetRatesRequest(s *capnp.Segment) (GetRatesRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return GetRatesRequest(st), err
}

func NewRootGetRatesRequest(s *capnp.Segment) (GetRatesRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3})
	return GetRatesRequest(st), err
}

func ReadRootGetRatesRequest(msg *capnp.Message) (GetRatesRequest, error) {
	root, err := msg.Root()
	return GetRatesRequest(root.Struct()), err
}

func (s GetRatesRequest) String() string {
	str, _ := text.Marshal(0xacd4e4ca3937ac30, capnp.Struct(s))
	return str
}

func (s GetRatesRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetRatesRequest) DecodeFromPtr(p capnp.Ptr) GetRatesRequest {
	return GetRatesRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetRatesRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GetRatesRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetRatesRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetRatesRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GetRatesRequest) HotelIds() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s GetRatesRequest) HasHotelIds() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetRatesRequest) SetHotelIds(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewHotelIds sets the hotelIds field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s GetRatesRequest) NewHotelIds(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}
func (s GetRatesRequest) InDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s GetRatesRequest) HasInDate() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s GetRatesRequest) InDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s GetRatesRequest) SetInDate(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s GetRatesRequest) OutDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s GetRatesRequest) HasOutDate() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s GetRatesRequest) OutDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s GetRatesRequest) SetOutDate(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// GetRatesRequest_List is a list of GetRatesRequest.
type GetRatesRequest_List = capnp.StructList[GetRatesRequest]

// NewGetRatesRequest creates a new list of GetRatesRequest.
func NewGetRatesRequest_List(s *capnp.Segment, sz int32) (GetRatesRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 3}, sz)
	return capnp.StructList[GetRatesRequest](l), err
}

// GetRatesRequest_Future is a wrapper for a GetRatesRequest promised by a client call.
type GetRatesRequest_Future struct{ *capnp.Future }

func (f GetRatesRequest_Future) Struct() (GetRatesRequest, error) {
	p, err := f.Future.Ptr()
	return GetRatesRequest(p.Struct()), err
}

type GetRatesResult capnp.Struct

// GetRatesResult_TypeID is the unique identifier for the type GetRatesResult.
const GetRatesResult_TypeID = 0xc6765c768f2860da

func NewGetRatesResult(s *capnp.Segment) (GetRatesResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetRatesResult(st), err
}

func NewRootGetRatesResult(s *capnp.Segment) (GetRatesResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return GetRatesResult(st), err
}

func ReadRootGetRatesResult(msg *capnp.Message) (GetRatesResult, error) {
	root, err := msg.Root()
	return GetRatesResult(root.Struct()), err
}

func (s GetRatesResult) String() string {
	str, _ := text.Marshal(0xc6765c768f2860da, capnp.Struct(s))
	return str
}

func (s GetRatesResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (GetRatesResult) DecodeFromPtr(p capnp.Ptr) GetRatesResult {
	return GetRatesResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s GetRatesResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s GetRatesResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s GetRatesResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s GetRatesResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s GetRatesResult) RatePlans() (RatePlan_List, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return RatePlan_List(p.List()), err
}

func (s GetRatesResult) HasRatePlans() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s GetRatesResult) SetRatePlans(v RatePlan_List) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewRatePlans sets the ratePlans field to a newly
// allocated RatePlan_List, preferring placement in s's segment.
func (s GetRatesResult) NewRatePlans(n int32) (RatePlan_List, error) {
	l, err := NewRatePlan_List(capnp.Struct(s).Segment(), n)
	if err != nil {
		return RatePlan_List{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// GetRatesResult_List is a list of GetRatesResult.
type GetRatesResult_List = capnp.StructList[GetRatesResult]

// NewGetRatesResult creates a new list of GetRatesResult.
func NewGetRatesResult_List(s *capnp.Segment, sz int32) (GetRatesResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[GetRatesResult](l), err
}

// GetRatesResult_Future is a wrapper for a GetRatesResult promised by a client call.
type GetRatesResult_Future struct{ *capnp.Future }

func (f GetRatesResult_Future) Struct() (GetRatesResult, error) {
	p, err := f.Future.Ptr()
	return GetRatesResult(p.Struct()), err
}

type RatePlan capnp.Struct

// RatePlan_TypeID is the unique identifier for the type RatePlan.
const RatePlan_TypeID = 0xaf23ad85cf760f6c

func NewRatePlan(s *capnp.Segment) (RatePlan, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 5})
	return RatePlan(st), err
}

func NewRootRatePlan(s *capnp.Segment) (RatePlan, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 5})
	return RatePlan(st), err
}

func ReadRootRatePlan(msg *capnp.Message) (RatePlan, error) {
	root, err := msg.Root()
	return RatePlan(root.Struct()), err
}

func (s RatePlan) String() string {
	str, _ := text.Marshal(0xaf23ad85cf760f6c, capnp.Struct(s))
	return str
}

func (s RatePlan) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RatePlan) DecodeFromPtr(p capnp.Ptr) RatePlan {
	return RatePlan(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RatePlan) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RatePlan) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RatePlan) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RatePlan) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RatePlan) HotelId() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RatePlan) HasHotelId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RatePlan) HotelIdBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RatePlan) SetHotelId(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s RatePlan) Code() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s RatePlan) HasCode() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RatePlan) CodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s RatePlan) SetCode(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s RatePlan) InDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s RatePlan) HasInDate() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s RatePlan) InDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s RatePlan) SetInDate(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s RatePlan) OutDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s RatePlan) HasOutDate() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s RatePlan) OutDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s RatePlan) SetOutDate(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s RatePlan) RoomType() (RoomType, error) {
	p, err := capnp.Struct(s).Ptr(4)
	return RoomType(p.Struct()), err
}

func (s RatePlan) HasRoomType() bool {
	return capnp.Struct(s).HasPtr(4)
}

func (s RatePlan) SetRoomType(v RoomType) error {
	return capnp.Struct(s).SetPtr(4, capnp.Struct(v).ToPtr())
}

// NewRoomType sets the roomType field to a newly
// allocated RoomType struct, preferring placement in s's segment.
func (s RatePlan) NewRoomType() (RoomType, error) {
	ss, err := NewRoomType(capnp.Struct(s).Segment())
	if err != nil {
		return RoomType{}, err
	}
	err = capnp.Struct(s).SetPtr(4, capnp.Struct(ss).ToPtr())
	return ss, err
}

// RatePlan_List is a list of RatePlan.
type RatePlan_List = capnp.StructList[RatePlan]

// NewRatePlan creates a new list of RatePlan.
func NewRatePlan_List(s *capnp.Segment, sz int32) (RatePlan_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 5}, sz)
	return capnp.StructList[RatePlan](l), err
}

// RatePlan_Future is a wrapper for a RatePlan promised by a client call.
type RatePlan_Future struct{ *capnp.Future }

func (f RatePlan_Future) Struct() (RatePlan, error) {
	p, err := f.Future.Ptr()
	return RatePlan(p.Struct()), err
}
func (p RatePlan_Future) RoomType() RoomType_Future {
	return RoomType_Future{Future: p.Future.Field(4, nil)}
}

type RoomType capnp.Struct

// RoomType_TypeID is the unique identifier for the type RoomType.
const RoomType_TypeID = 0xa7260ff7cf9bcd64

func NewRoomType(s *capnp.Segment) (RoomType, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return RoomType(st), err
}

func NewRootRoomType(s *capnp.Segment) (RoomType, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3})
	return RoomType(st), err
}

func ReadRootRoomType(msg *capnp.Message) (RoomType, error) {
	root, err := msg.Root()
	return RoomType(root.Struct()), err
}

func (s RoomType) String() string {
	str, _ := text.Marshal(0xa7260ff7cf9bcd64, capnp.Struct(s))
	return str
}

func (s RoomType) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (RoomType) DecodeFromPtr(p capnp.Ptr) RoomType {
	return RoomType(capnp.Struct{}.DecodeFromPtr(p))
}

func (s RoomType) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s RoomType) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s RoomType) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s RoomType) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s RoomType) BookableRate() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(0))
}

func (s RoomType) SetBookableRate(v float64) {
	capnp.Struct(s).SetUint64(0, math.Float64bits(v))
}

func (s RoomType) TotalRate() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(8))
}

func (s RoomType) SetTotalRate(v float64) {
	capnp.Struct(s).SetUint64(8, math.Float64bits(v))
}

func (s RoomType) TotalRateInclusive() float64 {
	return math.Float64frombits(capnp.Struct(s).Uint64(16))
}

func (s RoomType) SetTotalRateInclusive(v float64) {
	capnp.Struct(s).SetUint64(16, math.Float64bits(v))
}

func (s RoomType) Code() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s RoomType) HasCode() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s RoomType) CodeBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s RoomType) SetCode(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s RoomType) Currency() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s RoomType) HasCurrency() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s RoomType) CurrencyBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s RoomType) SetCurrency(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s RoomType) RoomDescription() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s RoomType) HasRoomDescription() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s RoomType) RoomDescriptionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s RoomType) SetRoomDescription(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// RoomType_List is a list of RoomType.
type RoomType_List = capnp.StructList[RoomType]

// NewRoomType creates a new list of RoomType.
func NewRoomType_List(s *capnp.Segment, sz int32) (RoomType_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 24, PointerCount: 3}, sz)
	return capnp.StructList[RoomType](l), err
}

// RoomType_Future is a wrapper for a RoomType promised by a client call.
type RoomType_Future struct{ *capnp.Future }

func (f RoomType_Future) Struct() (RoomType, error) {
	p, err := f.Future.Ptr()
	return RoomType(p.Struct()), err
}

type ReservationRequest capnp.Struct

// ReservationRequest_TypeID is the unique identifier for the type ReservationRequest.
const ReservationRequest_TypeID = 0xe9321e9a1b786747

func NewReservationRequest(s *capnp.Segment) (ReservationRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return ReservationRequest(st), err
}

func NewRootReservationRequest(s *capnp.Segment) (ReservationRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4})
	return ReservationRequest(st), err
}

func ReadRootReservationRequest(msg *capnp.Message) (ReservationRequest, error) {
	root, err := msg.Root()
	return ReservationRequest(root.Struct()), err
}

func (s ReservationRequest) String() string {
	str, _ := text.Marshal(0xe9321e9a1b786747, capnp.Struct(s))
	return str
}

func (s ReservationRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ReservationRequest) DecodeFromPtr(p capnp.Ptr) ReservationRequest {
	return ReservationRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ReservationRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ReservationRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ReservationRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ReservationRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ReservationRequest) CustomerName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ReservationRequest) HasCustomerName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ReservationRequest) CustomerNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ReservationRequest) SetCustomerName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ReservationRequest) HotelId() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return capnp.TextList(p.List()), err
}

func (s ReservationRequest) HasHotelId() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ReservationRequest) SetHotelId(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(1, v.ToPtr())
}

// NewHotelId sets the hotelId field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s ReservationRequest) NewHotelId(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(1, l.ToPtr())
	return l, err
}
func (s ReservationRequest) InDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ReservationRequest) HasInDate() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ReservationRequest) InDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ReservationRequest) SetInDate(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ReservationRequest) OutDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.Text(), err
}

func (s ReservationRequest) HasOutDate() bool {
	return capnp.Struct(s).HasPtr(3)
}

func (s ReservationRequest) OutDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(3)
	return p.TextBytes(), err
}

func (s ReservationRequest) SetOutDate(v string) error {
	return capnp.Struct(s).SetText(3, v)
}

func (s ReservationRequest) RoomNumber() int32 {
	return int32(capnp.Struct(s).Uint32(0))
}

func (s ReservationRequest) SetRoomNumber(v int32) {
	capnp.Struct(s).SetUint32(0, uint32(v))
}

// ReservationRequest_List is a list of ReservationRequest.
type ReservationRequest_List = capnp.StructList[ReservationRequest]

// NewReservationRequest creates a new list of ReservationRequest.
func NewReservationRequest_List(s *capnp.Segment, sz int32) (ReservationRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 4}, sz)
	return capnp.StructList[ReservationRequest](l), err
}

// ReservationRequest_Future is a wrapper for a ReservationRequest promised by a client call.
type ReservationRequest_Future struct{ *capnp.Future }

func (f ReservationRequest_Future) Struct() (ReservationRequest, error) {
	p, err := f.Future.Ptr()
	return ReservationRequest(p.Struct()), err
}

type ReservationResult capnp.Struct

// ReservationResult_TypeID is the unique identifier for the type ReservationResult.
const ReservationResult_TypeID = 0x9636be3292edef59

func NewReservationResult(s *capnp.Segment) (ReservationResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ReservationResult(st), err
}

func NewRootReservationResult(s *capnp.Segment) (ReservationResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return ReservationResult(st), err
}

func ReadRootReservationResult(msg *capnp.Message) (ReservationResult, error) {
	root, err := msg.Root()
	return ReservationResult(root.Struct()), err
}

func (s ReservationResult) String() string {
	str, _ := text.Marshal(0x9636be3292edef59, capnp.Struct(s))
	return str
}

func (s ReservationResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ReservationResult) DecodeFromPtr(p capnp.Ptr) ReservationResult {
	return ReservationResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ReservationResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ReservationResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ReservationResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ReservationResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ReservationResult) HotelId() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s ReservationResult) HasHotelId() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ReservationResult) SetHotelId(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewHotelId sets the hotelId field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s ReservationResult) NewHotelId(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// ReservationResult_List is a list of ReservationResult.
type ReservationResult_List = capnp.StructList[ReservationResult]

// NewReservationResult creates a new list of ReservationResult.
func NewReservationResult_List(s *capnp.Segment, sz int32) (ReservationResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[ReservationResult](l), err
}

// ReservationResult_Future is a wrapper for a ReservationResult promised by a client call.
type ReservationResult_Future struct{ *capnp.Future }

func (f ReservationResult_Future) Struct() (ReservationResult, error) {
	p, err := f.Future.Ptr()
	return ReservationResult(p.Struct()), err
}

type SearchRequest capnp.Struct

// SearchRequest_TypeID is the unique identifier for the type SearchRequest.
const SearchRequest_TypeID = 0xcb2900c3c91ac621

func NewSearchRequest(s *capnp.Segment) (SearchRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return SearchRequest(st), err
}

func NewRootSearchRequest(s *capnp.Segment) (SearchRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2})
	return SearchRequest(st), err
}

func ReadRootSearchRequest(msg *capnp.Message) (SearchRequest, error) {
	root, err := msg.Root()
	return SearchRequest(root.Struct()), err
}

func (s SearchRequest) String() string {
	str, _ := text.Marshal(0xcb2900c3c91ac621, capnp.Struct(s))
	return str
}

func (s SearchRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SearchRequest) DecodeFromPtr(p capnp.Ptr) SearchRequest {
	return SearchRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SearchRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SearchRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SearchRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SearchRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SearchRequest) Lat() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(0))
}

func (s SearchRequest) SetLat(v float32) {
	capnp.Struct(s).SetUint32(0, math.Float32bits(v))
}

func (s SearchRequest) Lon() float32 {
	return math.Float32frombits(capnp.Struct(s).Uint32(4))
}

func (s SearchRequest) SetLon(v float32) {
	capnp.Struct(s).SetUint32(4, math.Float32bits(v))
}

func (s SearchRequest) InDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s SearchRequest) HasInDate() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SearchRequest) InDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s SearchRequest) SetInDate(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s SearchRequest) OutDate() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s SearchRequest) HasOutDate() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s SearchRequest) OutDateBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s SearchRequest) SetOutDate(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// SearchRequest_List is a list of SearchRequest.
type SearchRequest_List = capnp.StructList[SearchRequest]

// NewSearchRequest creates a new list of SearchRequest.
func NewSearchRequest_List(s *capnp.Segment, sz int32) (SearchRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 2}, sz)
	return capnp.StructList[SearchRequest](l), err
}

// SearchRequest_Future is a wrapper for a SearchRequest promised by a client call.
type SearchRequest_Future struct{ *capnp.Future }

func (f SearchRequest_Future) Struct() (SearchRequest, error) {
	p, err := f.Future.Ptr()
	return SearchRequest(p.Struct()), err
}

type SearchResult capnp.Struct

// SearchResult_TypeID is the unique identifier for the type SearchResult.
const SearchResult_TypeID = 0x8d87418e975dca35

func NewSearchResult(s *capnp.Segment) (SearchResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SearchResult(st), err
}

func NewRootSearchResult(s *capnp.Segment) (SearchResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1})
	return SearchResult(st), err
}

func ReadRootSearchResult(msg *capnp.Message) (SearchResult, error) {
	root, err := msg.Root()
	return SearchResult(root.Struct()), err
}

func (s SearchResult) String() string {
	str, _ := text.Marshal(0x8d87418e975dca35, capnp.Struct(s))
	return str
}

func (s SearchResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (SearchResult) DecodeFromPtr(p capnp.Ptr) SearchResult {
	return SearchResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s SearchResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s SearchResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s SearchResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s SearchResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s SearchResult) HotelIds() (capnp.TextList, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return capnp.TextList(p.List()), err
}

func (s SearchResult) HasHotelIds() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s SearchResult) SetHotelIds(v capnp.TextList) error {
	return capnp.Struct(s).SetPtr(0, v.ToPtr())
}

// NewHotelIds sets the hotelIds field to a newly
// allocated capnp.TextList, preferring placement in s's segment.
func (s SearchResult) NewHotelIds(n int32) (capnp.TextList, error) {
	l, err := capnp.NewTextList(capnp.Struct(s).Segment(), n)
	if err != nil {
		return capnp.TextList{}, err
	}
	err = capnp.Struct(s).SetPtr(0, l.ToPtr())
	return l, err
}

// SearchResult_List is a list of SearchResult.
type SearchResult_List = capnp.StructList[SearchResult]

// NewSearchResult creates a new list of SearchResult.
func NewSearchResult_List(s *capnp.Segment, sz int32) (SearchResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 1}, sz)
	return capnp.StructList[SearchResult](l), err
}

// SearchResult_Future is a wrapper for a SearchResult promised by a client call.
type SearchResult_Future struct{ *capnp.Future }

func (f SearchResult_Future) Struct() (SearchResult, error) {
	p, err := f.Future.Ptr()
	return SearchResult(p.Struct()), err
}

type CheckUserRequest capnp.Struct

// CheckUserRequest_TypeID is the unique identifier for the type CheckUserRequest.
const CheckUserRequest_TypeID = 0xb7f15a2c9b02027b

func NewCheckUserRequest(s *capnp.Segment) (CheckUserRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CheckUserRequest(st), err
}

func NewRootCheckUserRequest(s *capnp.Segment) (CheckUserRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2})
	return CheckUserRequest(st), err
}

func ReadRootCheckUserRequest(msg *capnp.Message) (CheckUserRequest, error) {
	root, err := msg.Root()
	return CheckUserRequest(root.Struct()), err
}

func (s CheckUserRequest) String() string {
	str, _ := text.Marshal(0xb7f15a2c9b02027b, capnp.Struct(s))
	return str
}

func (s CheckUserRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CheckUserRequest) DecodeFromPtr(p capnp.Ptr) CheckUserRequest {
	return CheckUserRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CheckUserRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CheckUserRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CheckUserRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CheckUserRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CheckUserRequest) Username() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s CheckUserRequest) HasUsername() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s CheckUserRequest) UsernameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s CheckUserRequest) SetUsername(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s CheckUserRequest) Password() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s CheckUserRequest) HasPassword() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s CheckUserRequest) PasswordBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s CheckUserRequest) SetPassword(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

// CheckUserRequest_List is a list of CheckUserRequest.
type CheckUserRequest_List = capnp.StructList[CheckUserRequest]

// NewCheckUserRequest creates a new list of CheckUserRequest.
func NewCheckUserRequest_List(s *capnp.Segment, sz int32) (CheckUserRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 0, PointerCount: 2}, sz)
	return capnp.StructList[CheckUserRequest](l), err
}

// CheckUserRequest_Future is a wrapper for a CheckUserRequest promised by a client call.
type CheckUserRequest_Future struct{ *capnp.Future }

func (f CheckUserRequest_Future) Struct() (CheckUserRequest, error) {
	p, err := f.Future.Ptr()
	return CheckUserRequest(p.Struct()), err
}

type CheckUserResult capnp.Struct

// CheckUserResult_TypeID is the unique identifier for the type CheckUserResult.
const CheckUserResult_TypeID = 0xd2e733ae7aab55b1

func NewCheckUserResult(s *capnp.Segment) (CheckUserResult, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CheckUserResult(st), err
}

func NewRootCheckUserResult(s *capnp.Segment) (CheckUserResult, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0})
	return CheckUserResult(st), err
}

func ReadRootCheckUserResult(msg *capnp.Message) (CheckUserResult, error) {
	root, err := msg.Root()
	return CheckUserResult(root.Struct()), err
}

func (s CheckUserResult) String() string {
	str, _ := text.Marshal(0xd2e733ae7aab55b1, capnp.Struct(s))
	return str
}

func (s CheckUserResult) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (CheckUserResult) DecodeFromPtr(p capnp.Ptr) CheckUserResult {
	return CheckUserResult(capnp.Struct{}.DecodeFromPtr(p))
}

func (s CheckUserResult) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s CheckUserResult) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s CheckUserResult) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s CheckUserResult) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s CheckUserResult) Correct() bool {
	return capnp.Struct(s).Bit(0)
}

func (s CheckUserResult) SetCorrect(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

// CheckUserResult_List is a list of CheckUserResult.
type CheckUserResult_List = capnp.StructList[CheckUserResult]

// NewCheckUserResult creates a new list of CheckUserResult.
func NewCheckUserResult_List(s *capnp.Segment, sz int32) (CheckUserResult_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 0}, sz)
	return capnp.StructList[CheckUserResult](l), err
}

// CheckUserResult_Future is a wrapper for a CheckUserResult promised by a client call.
type CheckUserResult_Future struct{ *capnp.Future }

func (f CheckUserResult_Future) Struct() (CheckUserResult, error) {
	p, err := f.Future.Ptr()
	return CheckUserResult(p.Struct()), err
}

const schema_a1b2c3d4e5f6a7b8 = "x\xda\xacW\x7f\x8c\x1cu\x15\x7f\x9f\xefw\xf6\xb6\xbd" +
	"\xbb\xde\xeef\xb6I\x0b\xa9\x15$\xa6m,\xe9\xdd\x89" +
	"\xe8\x05=z\xadi\xaf\xc1\xcb}W\x1a\xf1R\xb4s" +
	"\xbb_z\x0b\xb3;\xc7\xcc\xec\x95\x13\x9b\xaa\xa1\xc1\x1a" +
	"\xaaP\x0d\xf2C\x12.\x01\xb1\xd0R\x0b4\x16c\x0c" +
	"\x88\x81\x88 `\x88\xa1\x06\x7f\x90\xb4\xc1\x0b4\xfc\x88" +
	"\x8a\x8d\xe2\x9a7\xbb;3\x9d\xee\x1e5\xfa\xdf\xec\x9b" +
	"7\xef}\xde{\x9f\xf7c\xd7-M]n\xf4/y" +
	"+MBmKu\xd5/y\xf6\xea\xef\x7f{\xfd\xcd" +
	"\xfb(\xb7\x0c\xf5c\x0f\xfc\xfd\xe4\xcbO=2G)" +
	"\xa4\x89\x06\xff \xd7\xc0<%\xd3D\xe6\xbc\x1c&\xd4" +
	"\xb3\x0f\x8e\xae\xf0\x0f=tk;\xe5\x15\xc6\xb7`^" +
	"b\xb0r\xbf\xc1\xca_|\xeb\xd4\xfe\x81\x9f\x7f\xe2\xf6" +
	"v\xca\xda(\xc0\x9c\x0d\x94k\x81\xf2\xd2Mo,\xaf" +
	"l=<Gj\x19\x92\xda\xe6\xfd\xc6\xbb\xe6\x91@\xf9" +
	"\x90\xb1\x93P/=\x7f\xf7\x0b\xefe>\xfa\x00+\xcb" +
	"\x982#\x1d\\\x9c\xea\x86\xb9<\xc5\x8fKS_\x00" +
	"\xa1\xbez\xd5\xa3\xcf?\xba\xff\xbe\x07\xdb\xd9\x1e\x9c\xed" +
	"\x1a\x80\xb9\xb7\x8b\x8d\xef\xe9:L\xa8\xaf;x\xe9\xa7" +
	"\x9e=\xf1\xf2\xc1\x04\xec\xc0\xf6\x05\xe9\x11\x98\xfdiV" +
	"^\x9bfe;3\xf3\xc2\x9eC\x1f9\x9cP\x0e\xbc" +
	"\x1fOw\xc3\x9cg\xe5\xc1\x93\xe9\x95\x0cd\xf8\x8f\x8b" +
	"\xe7o\xfe\xcc\x8d\x8f$\x81\xb0\xf7\xc1\xd3\x8b\x04\xcc\xd4" +
	"b~\xc4\xe2gX\xfd\xfc\x7f\xef\xfc\xe1\xe4\xec{\x8f" +
	"\xb1\xbaH\xe2~\xa9{?\xcc\xf9n\x86r\xb2\x9b\xa1" +
	"\xdc(\xc4\xdd\x1f\x9bx\xe7'\x09(\x82\x95w\xf5l" +
	"\x81y[\x0f+\xef\xeb\xe1\x0c\xfe~\xfb\xaa\xef\xccl" +
	"\x9by\xba]m\xde\xe9\x19\x82\x89^V~\xbfg\x98" +
	"\xf0\xa7\x0b\x9e>\xefWO\xad\xfeu\x02t`\xb8\xbf" +
	"w\x00\xe6\xfa@\xf7\xd3\xbd\xaf\x13\xea\xc7G\x9fy\xe3" +
	"K\x03?\xfdM\xc2p\x90\xdf\xdc\x92w\xcd\x15K\xf8" +
	"\xb3\xe5K\x82\xc2\x1c\xd9\xfa\xd0W\x1e\x1e|\xfd\xb7\x89" +
	"|\x18\x01\xe4\xbe\x11\x98\xfb\xfa\xf8\xbb\xbd}\xcc\x90\x0d" +
	"On\xda\xfe\xa2\xe8\xfb];\xc8\x07\xfa\xd6\xc0|<" +
	"P>\x1a(_z\xff'o\xbfm\xe4\xe1W\xda%" +
	"c\xbeo\x02\xe6\xfb\x81\xf2\xe9>N\xc6\xa6\x1d7\x9c" +
	"\x7f\xd7\x87\x06\xe6\x93e\x09p\x943\x130we\x02" +
	"\xaad\x82*>\xf1\xdd\xe3\x17\xbff\xfc\xe2\x9f\xed\x80" +
	"\xcce\x0b0\x8ff\xd9\xf6\x91\xec0\xad\xadO9\xbe" +
	"\xb6\xbf\xecj\xe9iw\xc6\xf2\xcbN\xf5\xe2\xa25]" +
	"\x9d\x1e\xfa\xbc\xb6\xdc\xe2TAg\xbc\x9a\xed\x8f\x03\xca" +
	"\x90\x06\x91\x01\xa2\xdc\x92-D\xaaWB\xad\x12h\x18" +
	"\x18-yD\x84>\xc2\xb8\x04zI\xf0ch;\x95" +
	"\xb4\xbdI\xfb\x05]t*\x15]-\x05r\xaf\xa0\xd9" +
	"\x0d\xd1\xff\xe6\xc8H:*\xe8P\x12x@2\x92\x11" +
	"\"\xb5HB]$\xb0\xbb\xe9\xa0\x93q\x914\xber" +
	"\xb4b\xed\xd0lpQhp\xf5\x85D\xea\"\x09\xb5" +
	"N\x00\xc8\x83ek\xd9\xc9*\x09\xf5q\x81t\xcd\xb5" +
	"\x03\xcb\xbd\x84\xdd%}\x8dU\xb3}\x80\x04\x10\xf3t" +
	"V-\x0a\x8eS\xb9rvZ7\xf2\xb3,\xf4v\xe7" +
	"\xb5D\xea\x0e\x09u\x9f@\xae\xe5n\xae@\xa4\xee\x95" +
	"P\x07\x05rB\xe4!\x88r\x07\xee\"R\x07%\xd4" +
	"1\x01\xc8<$Q\xee\xe8\x1a\"\xf5c\x09\xf53\x81" +
	"\x9c\x81<\x0c\xa2\xdc\xe3\x9c\xf2c\x12\xea\x97\x02\xb9\x94" +
	"\xc8#E\x94{\xf2\x1bD\xea\x09\x09\xf5\x9c@}\xd2" +
	"q\xae\xb3&mM\x99\x82\xe5k\xf4\x90@\x0f\xa1\xee" +
	";\xbee\x17,\x9fp\xb6\x0cz\xb4Z\xb4k^Y" +
	"\xce\x84/3E\xa7\xa4[\xa9\xa8\x17k\xae\xab\xab\xc5" +
	"Y.nK\xe6:Ne\xa3\xf6\x8ap\xcb\xd3\x9c\x8c" +
	"\xe8M\xc7D\x8di\xcb\x9d\x9c-\xe8\x95\xd7\xd7\xb4\x17" +
	"\xd4\xba7L\xd6g\xb94\x97K\xa8+b\xc9\x1ae" +
	"\xe1F\x095.\x80f\xae>\xc7\x09\xbcBB]%" +
	"\x90\xb6-\x1f\xdd$\xd0MH\xdbN\xb5\xf5\\\xb7-" +
	"\xdf\xf3\xddr\x95\xb0\xe3,XF;\xbe[\xbe\xf6\x0a" +
	":\xc0E\x09`[\x9a\x18\xb6\xc7\x80]=D\xa4\xae" +
	"\x92P\xa5X\x15-f\xd26\x095\xb5`?\x0c\x97" +
	"\xab\x1b\xb94-\x9e95?\xfe{\x01\x9eY\xbe\x1e" +
	"\xb7\xadj\x83g\xf9\x10\xe1.\xf6{\x83\x84\xba)\x86" +
	"\xf0\xebL\x9f\xafJ\xa8o\xc6\x10\xeea\xd8_\x93P" +
	"\xb7\x08\xe4d\x93h{\xf9\xf3\x9b$\xd4\xadL4\xa3" +
	"A\xb4}\x1c\xf5-\x12\xea\x8eX\xeb5\x11\x9e\xc1\x8d" +
	"\x0f\x8a\xc6\x0d\x9b\x83\x90\x8dV/\x01\xd9\x85b]_" +
	"*\xb9\xda\xf3\x82H?\x1cF\xfa\x12w\xd4\x8b\x12\xea" +
	"\xd5X\xa4\xc7'\x88\xd4+\x12\xeaD,\xd2\xd78\xfc" +
	"W%\xd4_b\x91\x9e\x1c R\x7f\x96Po\xc6\"" +
	"\x9d\xe7\xf0OH\xa8\xb7\xb9\xa5R\x8d\x96:\xc56\xdf" +
	"\x94P\xff\x10@W\x1e]D\xb9\xbf1\x19\xdf\x96P" +
	"\xff\x12\xc8\xa5\x91\xe7\x89\x9d;\xcd\xc2\xbfJ\x14 P" +
	"\xf7|Wk\x7f\xacF\x99\xca\xa4v\xc3\x144\xc5\x16" +
	"\xc9\x8a\x8erX\xf6g[?Vz~<\x85E\xa7" +
	"V\xf5\xdd\xf0m}\xda\xf1|\xcb\xde\xe0\x90\x8c\xd2\xde" +
	"\x91\xf9\xff\xd5Tg\xbe#\xd9\x88#Q#\xb6\xeb\xc3" +
	"\x9c@\xb3\x11Y\xb8YB])\xb0\xdb\xd5\xd7\xd7\xca" +
	"\xee\x99\xf0\x9a\xa3$\x80\xd7\x9a9\x1d\x9bp\xc3\x94." +
	"^\xb7\xd5\xd3n\xab\x0b)1\xba\xb7Dc:,}" +
	"?\x0b\xd7I\xa8\xcb\x04\xea5O\xbbU\xab\xa2\xe3C" +
	"j\xda\xf2\xbc\x9d\x8e[\x8a\xcb:r\xae5\x07\x86\x1b" +
	"\xeb.\xb1\x8b\x0a\xb1e\xe7\xb6:\x11^\xab\xb9\xb3\xd1" +
	"1G8c3u\xdc\xdd\xd1\x18\xcc\x86n\xac\x0b\xa3" +
	"\x19\x12\x86\xa9Y\xb8]B\xd9\xd1\x18,s+\x97$" +
	"\xd44\x13\x1c\x0d\x82W\xb8vS\x12\xca\xef<\x1b\xcf" +
	"u\xfc\x9c\xbdP7\xf3\x9b\xc4\x8a;\x8fH}OB" +
	"\xdd\x1b\x83{\xcf\x9a\xd8\xdek5\xe4\xdcdl\xef\xb5" +
	"\x1a\xf2\x00\x0b\x7f$\xa1\x1e\x8b5\xe4\x91\x91h\x19\x86" +
	"\x0dyt\xa8\xb9\x0d\x9f\x13\x90\xe5h\x14q\xc1\xa3j" +
	"O9U=V\xabP:\xde~%\xed\x15yGQ" +
	"\xba\xecT\xc3\xb0\xad\xc6\x80A6:\xab\x1b3i\xb8" +
	"\xccwC\xac\xae\xe1\x7f\x8bD]\x17\xa2pp.u" +
	"8f\xf2\x82[\xdcuu\xf1\x1cn\x8b\xd6\xca\xfc?" +
	"\xdcy\xed\xf6\xde\xb8\xeb\\S\xb6\x9b\xabO6\xc8\xd8" +
	"\xa6\xe76\xc6\xaa\xbb\x9e+q\x99\x84\xda\xbc\xf0\x96\xb3" +
	"\x9d\xa2e\xeb\x0f\xde\xbeg\x1c\x81\x11\x8a\xd8z\xbb6" +
	"\xb6\xc9Z(\xf6\x8c47\xd9\x0fb\x1c\xbbs(\xc6" +
	"\xc6\x16\xc7\xee\x19\x89\xd8\x88&\xc5\xe6&\"2\xd6\x8b" +
	"5\xcfw*\xda\xa5\xccX\x8cL\x1d\xee\xcdsYw" +
	"c\xb5\xca$I\xed\xc2 \x01\xe3\x9c+\xd0\xee\x00\x1e" +
	"\x8a\x0e\xe0\xe1\xc0J\x8c\x97\xe1\x7f\xa5\x06/\xff\x13\x00" +
	"\x00\xff\xff\xdc\xe3\xdbf"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_a1b2c3d4e5f6a7b8,
		Nodes: []uint64{
			0x8d87418e975dca35,
			0x90abad741d49aa10,
			0x9636be3292edef59,
			0xa1af556d19eb4715,
			0xa7260ff7cf9bcd64,
			0xaaa492b3cdb32829,
			0xacd4e4ca3937ac30,
			0xaf23ad85cf760f6c,
			0xb27b3e87e909de3f,
			0xb4f77962a677fe1b,
			0xb7f15a2c9b02027b,
			0xc6765c768f2860da,
			0xcb2900c3c91ac621,
			0xceba325eebc749d9,
			0xd2e733ae7aab55b1,
			0xd60e02d06047c143,
			0xd8ae42919638a537,
			0xe9321e9a1b786747,
			0xfbc204e12ed993c0,
		},
		Compressed: true,
	})
}
