// Code generated by protoc-gen-arpc. DO NOT EDIT.
package hotel_reservation

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
)

// GeoClient is the client API for Geo service.
type GeoClient interface {
	Nearby(ctx context.Context, req *NearbyRequest) (*NearbyResult, error)
}

type arpcGeoClient struct {
	client *rpc.Client
}

func NewGeoClient(client *rpc.Client) GeoClient {
	return &arpcGeoClient{client: client}
}

func (c *arpcGeoClient) Nearby(ctx context.Context, req *NearbyRequest) (*NearbyResult, error) {
	resp := new(NearbyResult)
	if err := c.client.Call(ctx, "Geo", "Nearby", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type GeoServer interface {
	Nearby(ctx context.Context, req *NearbyRequest) (*NearbyResult, context.Context, error)
}

func RegisterGeoServer(s *rpc.Server, srv GeoServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Geo",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"Nearby": {
				MethodName: "Nearby",
				Handler:    _Geo_Nearby_Handler,
			},
		},
	}, srv)
}
func _Geo_Nearby_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(NearbyRequest)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(GeoServer).Nearby(ctx, in)
	return out, newCtx, err
}

// ProfileClient is the client API for Profile service.
type ProfileClient interface {
	GetProfiles(ctx context.Context, req *GetProfilesRequest) (*GetProfilesResult, error)
}

type arpcProfileClient struct {
	client *rpc.Client
}

func NewProfileClient(client *rpc.Client) ProfileClient {
	return &arpcProfileClient{client: client}
}

func (c *arpcProfileClient) GetProfiles(ctx context.Context, req *GetProfilesRequest) (*GetProfilesResult, error) {
	resp := new(GetProfilesResult)
	if err := c.client.Call(ctx, "Profile", "GetProfiles", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type ProfileServer interface {
	GetProfiles(ctx context.Context, req *GetProfilesRequest) (*GetProfilesResult, context.Context, error)
}

func RegisterProfileServer(s *rpc.Server, srv ProfileServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Profile",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"GetProfiles": {
				MethodName: "GetProfiles",
				Handler:    _Profile_GetProfiles_Handler,
			},
		},
	}, srv)
}
func _Profile_GetProfiles_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(GetProfilesRequest)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(ProfileServer).GetProfiles(ctx, in)
	return out, newCtx, err
}

// RecommendationClient is the client API for Recommendation service.
type RecommendationClient interface {
	GetRecommendations(ctx context.Context, req *GetRecommendationsRequest) (*GetRecommendationsResult, error)
}

type arpcRecommendationClient struct {
	client *rpc.Client
}

func NewRecommendationClient(client *rpc.Client) RecommendationClient {
	return &arpcRecommendationClient{client: client}
}

func (c *arpcRecommendationClient) GetRecommendations(ctx context.Context, req *GetRecommendationsRequest) (*GetRecommendationsResult, error) {
	resp := new(GetRecommendationsResult)
	if err := c.client.Call(ctx, "Recommendation", "GetRecommendations", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type RecommendationServer interface {
	GetRecommendations(ctx context.Context, req *GetRecommendationsRequest) (*GetRecommendationsResult, context.Context, error)
}

func RegisterRecommendationServer(s *rpc.Server, srv RecommendationServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Recommendation",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"GetRecommendations": {
				MethodName: "GetRecommendations",
				Handler:    _Recommendation_GetRecommendations_Handler,
			},
		},
	}, srv)
}
func _Recommendation_GetRecommendations_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(GetRecommendationsRequest)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(RecommendationServer).GetRecommendations(ctx, in)
	return out, newCtx, err
}

// RateClient is the client API for Rate service.
type RateClient interface {
	GetRates(ctx context.Context, req *GetRatesRequest) (*GetRatesResult, error)
}

type arpcRateClient struct {
	client *rpc.Client
}

func NewRateClient(client *rpc.Client) RateClient {
	return &arpcRateClient{client: client}
}

func (c *arpcRateClient) GetRates(ctx context.Context, req *GetRatesRequest) (*GetRatesResult, error) {
	resp := new(GetRatesResult)
	if err := c.client.Call(ctx, "Rate", "GetRates", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type RateServer interface {
	GetRates(ctx context.Context, req *GetRatesRequest) (*GetRatesResult, context.Context, error)
}

func RegisterRateServer(s *rpc.Server, srv RateServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Rate",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"GetRates": {
				MethodName: "GetRates",
				Handler:    _Rate_GetRates_Handler,
			},
		},
	}, srv)
}
func _Rate_GetRates_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(GetRatesRequest)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(RateServer).GetRates(ctx, in)
	return out, newCtx, err
}

// ReservationClient is the client API for Reservation service.
type ReservationClient interface {
	MakeReservation(ctx context.Context, req *ReservationRequest) (*ReservationResult, error)
	CheckAvailability(ctx context.Context, req *ReservationRequest) (*ReservationResult, error)
}

type arpcReservationClient struct {
	client *rpc.Client
}

func NewReservationClient(client *rpc.Client) ReservationClient {
	return &arpcReservationClient{client: client}
}

func (c *arpcReservationClient) MakeReservation(ctx context.Context, req *ReservationRequest) (*ReservationResult, error) {
	resp := new(ReservationResult)
	if err := c.client.Call(ctx, "Reservation", "MakeReservation", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

func (c *arpcReservationClient) CheckAvailability(ctx context.Context, req *ReservationRequest) (*ReservationResult, error) {
	resp := new(ReservationResult)
	if err := c.client.Call(ctx, "Reservation", "CheckAvailability", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type ReservationServer interface {
	MakeReservation(ctx context.Context, req *ReservationRequest) (*ReservationResult, context.Context, error)
	CheckAvailability(ctx context.Context, req *ReservationRequest) (*ReservationResult, context.Context, error)
}

func RegisterReservationServer(s *rpc.Server, srv ReservationServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Reservation",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"MakeReservation": {
				MethodName: "MakeReservation",
				Handler:    _Reservation_MakeReservation_Handler,
			},
			"CheckAvailability": {
				MethodName: "CheckAvailability",
				Handler:    _Reservation_CheckAvailability_Handler,
			},
		},
	}, srv)
}
func _Reservation_MakeReservation_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(ReservationRequest)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(ReservationServer).MakeReservation(ctx, in)
	return out, newCtx, err
}
func _Reservation_CheckAvailability_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(ReservationRequest)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(ReservationServer).CheckAvailability(ctx, in)
	return out, newCtx, err
}

// SearchClient is the client API for Search service.
type SearchClient interface {
	Nearby(ctx context.Context, req *SearchRequest) (*SearchResult, error)
}

type arpcSearchClient struct {
	client *rpc.Client
}

func NewSearchClient(client *rpc.Client) SearchClient {
	return &arpcSearchClient{client: client}
}

func (c *arpcSearchClient) Nearby(ctx context.Context, req *SearchRequest) (*SearchResult, error) {
	resp := new(SearchResult)
	if err := c.client.Call(ctx, "Search", "Nearby", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type SearchServer interface {
	Nearby(ctx context.Context, req *SearchRequest) (*SearchResult, context.Context, error)
}

func RegisterSearchServer(s *rpc.Server, srv SearchServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Search",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"Nearby": {
				MethodName: "Nearby",
				Handler:    _Search_Nearby_Handler,
			},
		},
	}, srv)
}
func _Search_Nearby_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(SearchServer).Nearby(ctx, in)
	return out, newCtx, err
}

// UserClient is the client API for User service.
type UserClient interface {
	CheckUser(ctx context.Context, req *CheckUserRequest) (*CheckUserResult, error)
}

type arpcUserClient struct {
	client *rpc.Client
}

func NewUserClient(client *rpc.Client) UserClient {
	return &arpcUserClient{client: client}
}

func (c *arpcUserClient) CheckUser(ctx context.Context, req *CheckUserRequest) (*CheckUserResult, error) {
	resp := new(CheckUserResult)
	if err := c.client.Call(ctx, "User", "CheckUser", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type UserServer interface {
	CheckUser(ctx context.Context, req *CheckUserRequest) (*CheckUserResult, context.Context, error)
}

func RegisterUserServer(s *rpc.Server, srv UserServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "User",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"CheckUser": {
				MethodName: "CheckUser",
				Handler:    _User_CheckUser_Handler,
			},
		},
	}, srv)
}
func _User_CheckUser_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(CheckUserRequest)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(UserServer).CheckUser(ctx, in)
	return out, newCtx, err
}
