apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: user-fault-drop
spec:
  workloadSelector:
    labels:
      io.kompose.service: user
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: SIDECAR_INBOUND
      listener:
        portNumber: 8086
        filterChain:
          filter:
            name: "envoy.filters.network.http_connection_manager"
            subFilter:
              name: "envoy.filters.http.router"
    patch:
      operation: INSERT_BEFORE
      value: 
        name: envoy.filters.http.wasm
        typed_config:
          "@type": type.googleapis.com/envoy.extensions.filters.http.wasm.v3.Wasm
          config:
            name: fault_drop
            root_id: fault_drop
            vm_config:
              vm_id: vm.sentinel.acl-block-customer
              runtime: envoy.wasm.runtime.v8
              code:
                local:
                  filename: /etc/user_fault_drop.wasm
              allow_precompiled: false