// Code generated by protoc-gen-arpc. DO NOT EDIT.
package user

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
)

// UserClient is the client API for User service.
type UserClient interface {
	CheckUser(ctx context.Context, req *Request) (*Result, error)
}

type arpcUserClient struct {
	client *rpc.Client
}

func NewUserClient(client *rpc.Client) UserClient {
	return &arpcUserClient{client: client}
}

func (c *arpcUserClient) CheckUser(ctx context.Context, req *Request) (*Result, error) {
	resp := new(Result)
	if err := c.client.Call(ctx, "User", "CheckUser", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type UserServer interface {
	CheckUser(ctx context.Context, req *Request) (*Result, context.Context, error)
}

func RegisterUserServer(s *rpc.Server, srv UserServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "User",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"CheckUser": {
				MethodName: "CheckUser",
				Handler:    _User_CheckUser_Handler,
			},
		},
	}, srv)
}
func _User_CheckUser_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(UserServer).CheckUser(ctx, in)
	return out, newCtx, err
}
