// Code generated by protoc-gen-arpc. DO NOT EDIT.
package search

import (
	"context"
	"github.com/appnet-org/arpc/pkg/rpc"
)

// SearchClient is the client API for Search service.
type SearchClient interface {
	Nearby(ctx context.Context, req *NearbyRequest) (*SearchResult, error)
}

type arpcSearchClient struct {
	client *rpc.Client
}

func NewSearchClient(client *rpc.Client) SearchClient {
	return &arpcSearchClient{client: client}
}

func (c *arpcSearchClient) Nearby(ctx context.Context, req *NearbyRequest) (*SearchResult, error) {
	resp := new(SearchResult)
	if err := c.client.Call(ctx, "Search", "Nearby", req, resp); err != nil {
		return nil, err
	}
	return resp, nil
}

type SearchServer interface {
	Nearby(ctx context.Context, req *NearbyRequest) (*SearchResult, context.Context, error)
}

func RegisterSearchServer(s *rpc.Server, srv SearchServer) {
	s.RegisterService(&rpc.ServiceDesc{
		ServiceName: "Search",
		ServiceImpl: srv,
		Methods: map[string]*rpc.MethodDesc{
			"Nearby": {
				MethodName: "Nearby",
				Handler:    _Search_Nearby_Handler,
			},
		},
	}, srv)
}
func _Search_Nearby_Handler(srv any, ctx context.Context, dec func(any) error) (any, context.Context, error) {
	in := new(NearbyRequest)
	if err := dec(in); err != nil {
		return nil, ctx, err
	}
	out, newCtx, err := srv.(SearchServer).Nearby(ctx, in)
	return out, newCtx, err
}
