// Code generated by protoc-gen-symphony. DO NOT EDIT.
package search

import (
	"bytes"
	"encoding/binary"
)

func (m *NearbyRequest) MarshalSymphony() ([]byte, error) {
	var buf bytes.Buffer
	// Layout header and field ordering
	buf.WriteByte(0x00) // layout header
	buf.Write([]byte{1, 2, 3, 4})

	// Calculate offsets for variable-length fields
	offset := 0
	offset += 4 // Lat
	offset += 4 // Lon

	// Field 3 (InDate): string
	binary.Write(&buf, binary.LittleEndian, byte(3))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of InDate
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.InDate)))
	offset += len(m.InDate)
	// Field 4 (OutDate): string
	binary.Write(&buf, binary.LittleEndian, byte(4))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of OutDate
	binary.Write(&buf, binary.LittleEndian, uint16(len(m.OutDate)))
	offset += len(m.OutDate)

	// Write actual field data
	// Write fixed field Lat
	binary.Write(&buf, binary.LittleEndian, m.Lat)
	// Write fixed field Lon
	binary.Write(&buf, binary.LittleEndian, m.Lon)
	// Write string field InDate
	buf.Write([]byte(m.InDate))
	// Write string field OutDate
	buf.Write([]byte(m.OutDate))

	return buf.Bytes(), nil
}

func (m *NearbyRequest) UnmarshalSymphony(data []byte) error {
	// Parse header and field ordering
	reader := bytes.NewReader(data)
	var header byte
	if err := binary.Read(reader, binary.LittleEndian, &header); err != nil {
		return err
	}

	fieldOrder := make([]byte, 4)
	if _, err := reader.Read(fieldOrder); err != nil {
		return err
	}

	// Parse offset table for variable-length fields
	type offsetEntry struct{ offset, length uint16 }
	offsets := map[byte]offsetEntry{}
	for i := 0; i < 2; i++ {
		var fieldID byte
		var off, len uint16
		if err := binary.Read(reader, binary.LittleEndian, &fieldID); err != nil {
			return err
		}
		if err := binary.Read(reader, binary.LittleEndian, &off); err != nil {
			return err
		}
		if err := binary.Read(reader, binary.LittleEndian, &len); err != nil {
			return err
		}
		offsets[fieldID] = offsetEntry{off, len}
	}

	// Extract data region (everything after the offset table)
	dataRegion := data[len(data)-reader.Len():]

	// Unmarshal individual fields
	// Unmarshal fixed field Lat (field 1)
	if err := binary.Read(bytes.NewReader(dataRegion[0:4]), binary.LittleEndian, &m.Lat); err != nil {
		return err
	}
	// Unmarshal fixed field Lon (field 2)
	if err := binary.Read(bytes.NewReader(dataRegion[4:8]), binary.LittleEndian, &m.Lon); err != nil {
		return err
	}
	// Unmarshal string field InDate (field 3)
	if entry, ok := offsets[3]; ok {
		m.InDate = string(dataRegion[entry.offset : entry.offset+entry.length])
	}
	// Unmarshal string field OutDate (field 4)
	if entry, ok := offsets[4]; ok {
		m.OutDate = string(dataRegion[entry.offset : entry.offset+entry.length])
	}

	return nil
}

func (m *SearchResult) MarshalSymphony() ([]byte, error) {
	var buf bytes.Buffer
	// Layout header and field ordering
	buf.WriteByte(0x00) // layout header
	buf.Write([]byte{1})

	// Calculate offsets for variable-length fields
	offset := 0

	// Field 1 (HotelIds): repeated variable-length
	binary.Write(&buf, binary.LittleEndian, byte(1))
	binary.Write(&buf, binary.LittleEndian, uint16(offset)) // offset of HotelIds
	totalLen := 0
	for _, item := range m.HotelIds {
		totalLen += 4 + len(item) // 4 bytes for length + string data
	}
	binary.Write(&buf, binary.LittleEndian, uint16(totalLen))
	offset += totalLen

	// Write actual field data
	// Write repeated variable-length field HotelIds data
	for _, item := range m.HotelIds {
		binary.Write(&buf, binary.LittleEndian, uint32(len(item)))
		buf.Write([]byte(item))
	}

	return buf.Bytes(), nil
}

func (m *SearchResult) UnmarshalSymphony(data []byte) error {
	// Parse header and field ordering
	reader := bytes.NewReader(data)
	var header byte
	if err := binary.Read(reader, binary.LittleEndian, &header); err != nil {
		return err
	}

	fieldOrder := make([]byte, 1)
	if _, err := reader.Read(fieldOrder); err != nil {
		return err
	}

	// Parse offset table for variable-length fields
	type offsetEntry struct{ offset, length uint16 }
	offsets := map[byte]offsetEntry{}
	for i := 0; i < 1; i++ {
		var fieldID byte
		var off, len uint16
		if err := binary.Read(reader, binary.LittleEndian, &fieldID); err != nil {
			return err
		}
		if err := binary.Read(reader, binary.LittleEndian, &off); err != nil {
			return err
		}
		if err := binary.Read(reader, binary.LittleEndian, &len); err != nil {
			return err
		}
		offsets[fieldID] = offsetEntry{off, len}
	}

	// Extract data region (everything after the offset table)
	dataRegion := data[len(data)-reader.Len():]

	// Unmarshal individual fields
	// Unmarshal repeated variable-length field HotelIds (field 1)
	if entry, ok := offsets[1]; ok {
		// Initialize slice
		m.HotelIds = make([]string, 0)
		// Read repeated field data
		dataStart := entry.offset
		dataEnd := entry.offset + entry.length

		// Handle empty repeated field case
		if dataEnd > dataStart {
			itemReader := bytes.NewReader(dataRegion[dataStart:dataEnd])
			bytesRead := uint16(0)
			for bytesRead < entry.length {
				var itemLen uint32
				if err := binary.Read(itemReader, binary.LittleEndian, &itemLen); err != nil {
					return err
				}
				bytesRead += 4 // length of uint32

				// Handle empty string case
				if itemLen == 0 {
					m.HotelIds = append(m.HotelIds, "")
					continue
				}

				itemData := make([]byte, itemLen)
				if _, err := itemReader.Read(itemData); err != nil {
					return err
				}
				bytesRead += uint16(itemLen)
				m.HotelIds = append(m.HotelIds, string(itemData))
			}
		}
	}

	return nil
}
